/**
 * @module data-transformers/constants/content-labels-part1
 * @description CONTENT_LABELS for Northern/Western European languages: en, sv, da, no, fi, de, fr.
 * Part of the split CONTENT_LABELS constant — combined in content-labels.ts.
 *
 * @author Hack23 AB
 * @license Apache-2.0
 */

import type { ContentLabelSet } from '../../types/content.js';

export const CONTENT_LABELS_PART1: Partial<Record<string, ContentLabelSet>> = {
  en: {
    whyMatters: 'Why This Week Matters',
    whyMattersDefault: 'This week features significant parliamentary activity with key debates, committee meetings, and government consultations that will shape Sweden\'s political landscape.',
    keyEvents: 'Key Events This Week',
    whatToWatch: 'What to Watch',
    latestReports: 'Latest Committee Reports',
    noReports: 'No committee reports available at this time.',
    committee: 'Committee', document: 'Document',
    reportDefault: 'Committee report on parliamentary matter.',
    govProps: 'Government Propositions',
    noProps: 'No government propositions available at this time.',
    propDefault: 'Government proposal to Parliament.',
    oppMotions: 'Opposition Motions',
    noMotions: 'No opposition motions available at this time.',
    author: 'Author', party: 'Party',
    motionDefault: 'Parliamentary motion by opposition member.',
    genericContent: 'Content generation in progress.',
    monitorDev: 'Monitor developments and outcomes',
    committeeDebates: 'Committee Debates',
    committeeDebatesDesc: (n: number): string => `${n} committee reports scheduled for chamber debate`,
    govProposals: 'Government Proposals',
    govProposalsDesc: (n: number): string => `${n} new government propositions under review`,
    weekAhead: 'Week Ahead', committeeReportsTag: 'Committee Reports',
    govPropsTag: 'Government Propositions', oppMotionsTag: 'Opposition Motions', interpellationsTag: 'Interpellation Debates',
    // Enhanced summary labels
    committeeReport: 'committee report',
    on: 'on',
    governmentProposition: 'Government proposition',
    regarding: 'regarding',
    referredTo: 'referred to',
    motionBy: 'Motion by',
    parliamentaryMotion: 'Parliamentary motion',
    unknown: 'Unknown',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `The Swedish Parliament's committees have published ${n} new reports, reflecting ongoing legislative work across multiple policy areas.`,
    reportSignificance: 'This report addresses',
    readFullReport: 'Read the full report',
    propsOverview: (n: number): string => `The government has submitted ${n} new propositions to Parliament, each requiring committee review and chamber debate before potential adoption.`,
    propSignificance: 'This proposition concerns',
    readFullProp: 'Read the full proposition',
    motionsOverview: (n: number): string => `Opposition MPs have filed ${n} new motions, pressing the government on issues ranging across policy domains.`,
    motionSignificance: 'This motion addresses',
    readFullMotion: 'Read the full motion',
    interpellationDefault: 'Parliamentary interpellation demanding government accountability.',
    readFullInterpellation: 'Read the full interpellation',
    policyContext: 'Policy context',
    filedBy: 'Filed by',
    published: 'Published',
    politicalContext: 'Political Context',
    policyImplications: 'Policy Implications',
    keyTakeaways: 'Key Takeaways',
    thematicAnalysis: 'Thematic Analysis',
    legislativePipeline: 'Legislative Pipeline',
    oppositionStrategy: 'Opposition Strategy',
    coalitionDynamics: 'Coalition Dynamics',
    whatThisMeans: 'What This Means',
    whyItMatters: 'Why It Matters',
    committeeBreakdown: (n: number, c: number): string => `This batch of ${n} committee reports spans ${c} different committees, reflecting the breadth of legislative activity in the current parliamentary session. The thematic spread reveals the Riksdag's multi-front policy engagement and the government's legislative priorities.`,
    propsBreakdown: (n: number): string => `The government has submitted ${n} new propositions, signalling its policy priorities and the pace of its legislative agenda. Each proposition must navigate committee review and chamber debate, providing insight into the coalition's strategic direction and its ability to build cross-party support.`,
    motionsBreakdown: (n: number): string => `Opposition MPs have filed ${n} new motions, mapping the political fault lines in the current Riksdag. These motions reveal not just policy disagreements but the strategic positioning of parties as they prepare for the next electoral contest.`,
    noInterpellations: 'No interpellations available at this time.',
    interpellationsBreakdown: (n: number): string => `Opposition MPs have submitted ${n} interpellations to government ministers, demanding accountability and formal responses on pressing policy issues. Interpellations are among the most powerful tools of parliamentary oversight, forcing ministers to defend government decisions before the chamber.`,
    debateDynamics: 'Debate Dynamics & Accountability',
    ministerAccountability: 'Directed to',
    accountabilityAnalysis: 'Accountability Analysis',
    interpellationBy: 'Interpellation by',
    interpellationsScrutinyContext: (n: number): string => `Interpellations from ${n} different parties demonstrate broad parliamentary scrutiny of government ministers.`,
    interpellationsAccountabilityContext: (count: number, domains: number): string => `These ${count} interpellations span ${domains} policy domain${domains > 1 ? 's' : ''}, reflecting the breadth of parliamentary accountability demands on the government.`,
    committeeCountContext: (n: number): string => `${n} reports from this committee signal intensive legislative work within its portfolio.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `Parliamentary committees have been active across ${committees} and ${extra} further policy domains.` : `Parliamentary committees have been active across ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `A total of ${n} reports demonstrates sustained legislative momentum and ongoing policy prioritisation.`,
    oppositionStrategyContext: (n: number): string => `Motions from ${n} different parties reveal the breadth of opposition political criticism and alternative policy agendas.`,
    interpellationStrategyContext: (n: number): string => `Interpellations from ${n} different parties demonstrate coordinated parliamentary oversight and demands for government accountability.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `These ${propCount} propositions touch on ${domainCount} policy domain${domainCount > 1 ? 's' : ''}, demonstrating the government's broad legislative ambition. Committee review and chamber debate will determine whether these proposals command sufficient support to become law.`,
    genericOverview: (n: number): string => `During this period, ${n} documents were processed in parliament, offering a snapshot of ongoing legislative work.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} motion${n > 1 ? 's' : ''} filed`,
    partyInterpellationsFiled: (party: string, n: number): string => `${party}: ${n} interpellation${n > 1 ? 's' : ''} filed`,
    otherCommittee: 'Other committees',
    otherDocuments: 'Other documents',
    policySignificanceTouches: (domains: string): string => `Touches on ${domains}.`,
    policySignificanceGeneric: 'Requires committee review and chamber debate before a decision is reached.',
    processedThisPeriod: 'processed this period',
    generalMatters: 'General matters',
    responsesToProp: 'Responses to Government Propositions',
    independentMotions: 'Independent Motions',
    govEngagement: 'Government Department Engagement',
    twitterLabel1: 'Reading time',
    twitterLabel2: 'Article type',
    jobTitle: 'Political Intelligence Analyst',
    siteDescription: 'Swedish Parliament Intelligence Platform - Monitor political activity with systematic transparency',
    deepAnalysis: 'Deep Analysis',
    deepAnalysisWho: 'Key Actors',
    deepAnalysisWhat: 'What Happened',
    deepAnalysisWhen: 'Timeline & Context',
    deepAnalysisWhy: 'Why This Matters',
    deepAnalysisWinners: 'Winners & Losers',
    deepAnalysisImpact: 'Political Impact',
    deepAnalysisConsequences: 'Actions & Consequences',
    deepAnalysisCritical: 'Critical Assessment',
    deepAnalysisPerspectives: 'Multiple Perspectives',
    swotAnalysis: 'SWOT Analysis',
    swotStrengths: 'Strengths',
    swotWeaknesses: 'Weaknesses',
    swotOpportunities: 'Opportunities',
    swotThreats: 'Threats',
    swotContext: 'Context',
    swotImpactHigh: 'High',
    swotImpactMedium: 'Medium',
    swotImpactLow: 'Low',
    dashboardTitle: 'Dashboard',
    dashboardSummary: 'Summary'
  },
  sv: {
    whyMatters: 'Varför denna vecka är viktig',
    whyMattersDefault: 'Denna vecka innehåller betydande parlamentarisk aktivitet med viktiga debatter, kommittémöten och regeringskonsultationer som kommer att forma Sveriges politiska landskap.',
    keyEvents: 'Nyckelhändelser denna vecka',
    whatToWatch: 'Vad man ska följa',
    latestReports: 'Senaste kommittérapporter',
    noReports: 'Inga kommittérapporter tillgängliga för tillfället.',
    committee: 'Kommitté', document: 'Dokument',
    reportDefault: 'Kommittérapport om riksdagsärende.',
    govProps: 'Regeringens propositioner',
    noProps: 'Inga regeringspropositioner tillgängliga för tillfället.',
    propDefault: 'Regeringens förslag till riksdagen.',
    oppMotions: 'Oppositionens motioner',
    noMotions: 'Inga oppositionsmotioner tillgängliga för tillfället.',
    author: 'Författare', party: 'Parti',
    motionDefault: 'Riksdagsmotion av oppositionsmedlem.',
    genericContent: 'Innehållsgenerering pågår.',
    monitorDev: 'Övervaka utveckling och resultat',
    committeeDebates: 'Kommittédebatter',
    committeeDebatesDesc: (n: number): string => `${n} kommittérapporter planerade för kammarens debatt`,
    govProposals: 'Regeringsförslag',
    govProposalsDesc: (n: number): string => `${n} nya regeringspropositioner under granskning`,
    weekAhead: 'Veckan som kommer', committeeReportsTag: 'Kommittérapporter',
    govPropsTag: 'Regeringens propositioner', oppMotionsTag: 'Oppositionens motioner', interpellationsTag: 'Interpellationsdebatter',
    // Enhanced summary labels
    committeeReport: 'kommittérapport',
    on: 'om',
    governmentProposition: 'Regeringens proposition',
    regarding: 'angående',
    referredTo: 'hänvisad till',
    motionBy: 'Motion av',
    parliamentaryMotion: 'Riksdagsmotion',
    unknown: 'Okänd',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `Riksdagens utskott har publicerat ${n} nya betänkanden som speglar det pågående lagstiftningsarbetet inom flera politikområden.`,
    reportSignificance: 'Detta betänkande behandlar',
    readFullReport: 'Läs hela betänkandet',
    propsOverview: (n: number): string => `Regeringen har överlämnat ${n} nya propositioner till riksdagen, var och en kräver utskottsbehandling och kammardebatt.`,
    propSignificance: 'Denna proposition avser',
    readFullProp: 'Läs hela propositionen',
    motionsOverview: (n: number): string => `Oppositionsriksdagsledamöter har lämnat in ${n} nya motioner som pressar regeringen inom flera politikområden.`,
    motionSignificance: 'Denna motion behandlar',
    readFullMotion: 'Läs hela motionen',
    interpellationDefault: 'Riksdagsinterpellation som kräver regeringens ansvarsskyldighet.',
    readFullInterpellation: 'Läs hela interpellationen',
    policyContext: 'Politisk kontext',
    filedBy: 'Inlämnad av',
    published: 'Publicerad',
    politicalContext: 'Politisk kontext',
    policyImplications: 'Politiska konsekvenser',
    keyTakeaways: 'Centrala slutsatser',
    thematicAnalysis: 'Tematisk analys',
    legislativePipeline: 'Lagstiftningsprocess',
    oppositionStrategy: 'Oppositionens strategi',
    coalitionDynamics: 'Koalitionsdynamik',
    whatThisMeans: 'Vad detta innebär',
    whyItMatters: 'Varför det spelar roll',
    committeeBreakdown: (n: number, c: number): string => `Denna omgång med ${n} utskottsbetänkanden omfattar ${c} olika utskott, vilket speglar bredden i riksdagens lagstiftningsarbete under innevarande session.`,
    propsBreakdown: (n: number): string => `Regeringen har överlämnat ${n} nya propositioner, som signalerar dess politiska prioriteringar och takten i den lagstiftande agendan.`,
    motionsBreakdown: (n: number): string => `Oppositionsledamöter har lämnat in ${n} nya motioner som kartlägger de politiska skiljelinjerna i nuvarande riksdag.`,
    noInterpellations: 'Inga interpellationer tillgängliga för tillfället.',
    interpellationsBreakdown: (n: number): string => `Oppositionsledamöter har lämnat in ${n} interpellationer till regeringsministrar och kräver ansvarsskyldighet och formella svar i viktiga politikfrågor. Interpellationer är ett av riksdagens kraftfullaste verktyg för parlamentarisk kontroll och tvingar ministrar att försvara regeringsbeslut inför kammaren.`,
    debateDynamics: 'Debattdynamik och ansvarsutkrävande',
    ministerAccountability: 'Riktat till',
    accountabilityAnalysis: 'Ansvarsutkrävande',
    interpellationBy: 'Interpellation av',
    interpellationsScrutinyContext: (n: number): string => `Interpellationer från ${n} olika partier visar på bred parlamentarisk granskning av regeringens ministrar.`,
    interpellationsAccountabilityContext: (count: number, domains: number): string => `Dessa ${count} interpellationer spänner över ${domains} politikområde${domains > 1 ? 'n' : ''}, vilket avspeglar bredden i riksdagens ansvarsutkrävande av regeringen.`,
    committeeCountContext: (n: number): string => `${n} betänkanden från detta utskott signalerar intensivt lagstiftningsarbete inom dess ansvarsområde.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `Riksdagens utskott har varit aktiva inom ${committees} och ${extra} ytterligare områden.` : `Riksdagens utskott har varit aktiva inom ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `Totalt ${n} betänkanden visar lagstiftande momentum och pågående politisk prioritering.`,
    oppositionStrategyContext: (n: number): string => `Motioner från ${n} olika partier visar bredden i oppositionens politiska kritik och alternativa agenda.`,
    interpellationStrategyContext: (n: number): string => `Interpellationer från ${n} olika partier visar samordnad parlamentarisk granskning och krav på regeringsansvar.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `Dessa ${propCount} propositioner berör ${domainCount} politikområde${domainCount > 1 ? 'n' : ''}, vilket visar regeringens breda lagstiftningsambition. Utskottsbehandling och kammardebatt avgör om förslagen vinner tillräckligt stöd för att bli lag.`,
    genericOverview: (n: number): string => `Under perioden har ${n} dokument behandlats i riksdagen, vilket ger en bild av det pågående lagstiftningsarbetet.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} motion${n > 1 ? 'er' : ''} inlämnade`,
    partyInterpellationsFiled: (party: string, n: number): string => `${party}: ${n} interpellation${n > 1 ? 'er' : ''} inlämnade`,
    otherCommittee: 'Övriga utskott',
    otherDocuments: 'Övriga dokument',
    policySignificanceTouches: (domains: string): string => `Berör ${domains}.`,
    policySignificanceGeneric: 'Kräver utskottsbehandling och kammardebatt innan beslut fattas.',
    processedThisPeriod: 'behandlade denna period',
    generalMatters: 'Övriga frågor',
    responsesToProp: 'Svar på propositioner',
    independentMotions: 'Övriga motioner',
    govEngagement: 'Regeringsdepartementens engagemang',
    twitterLabel1: 'Lästid',
    twitterLabel2: 'Artikeltyp',
    jobTitle: 'Politisk underrättelseanalytiker',
    siteDescription: 'Riksdagsmonitor – övervaka politisk aktivitet med systematisk transparens',
    deepAnalysis: 'Djupanalys',
    deepAnalysisWho: 'Nyckelaktörer',
    deepAnalysisWhat: 'Vad som hände',
    deepAnalysisWhen: 'Tidslinje & kontext',
    deepAnalysisWhy: 'Varför det spelar roll',
    deepAnalysisWinners: 'Vinnare & förlorare',
    deepAnalysisImpact: 'Politisk påverkan',
    deepAnalysisConsequences: 'Handlingar & konsekvenser',
    deepAnalysisCritical: 'Kritisk bedömning',
    deepAnalysisPerspectives: 'Flera perspektiv',
    swotAnalysis: 'SWOT-analys',
    swotStrengths: 'Styrkor',
    swotWeaknesses: 'Svagheter',
    swotOpportunities: 'Möjligheter',
    swotThreats: 'Hot',
    swotContext: 'Kontext',
    swotImpactHigh: 'Hög',
    swotImpactMedium: 'Medel',
    swotImpactLow: 'Låg',
    dashboardTitle: 'Instrumentpanel',
    dashboardSummary: 'Sammanfattning'
  },
  da: {
    whyMatters: 'Hvorfor denne uge er vigtig',
    whyMattersDefault: 'Denne uge byder på vigtig parlamentarisk aktivitet med centrale debatter, udvalgsmøder og regeringskonsultationer.',
    keyEvents: 'Vigtige begivenheder denne uge',
    whatToWatch: 'Hvad man skal følge',
    latestReports: 'Seneste udvalgsbetænkninger',
    noReports: 'Ingen udvalgsbetænkninger tilgængelige på nuværende tidspunkt.',
    committee: 'Udvalg', document: 'Dokument',
    reportDefault: 'Udvalgsbetænkning om parlamentarisk sag.',
    govProps: 'Regeringsforslag',
    noProps: 'Ingen regeringsforslag tilgængelige på nuværende tidspunkt.',
    propDefault: 'Regeringsforslag til parlamentet.',
    oppMotions: 'Oppositionsforslag',
    noMotions: 'Ingen oppositionsforslag tilgængelige på nuværende tidspunkt.',
    author: 'Forfatter', party: 'Parti',
    motionDefault: 'Parlamentarisk forslag fra oppositionsmedlem.',
    genericContent: 'Indhold genereres.',
    monitorDev: 'Overvåg udviklingen og resultaterne',
    committeeDebates: 'Udvalgsedebatter',
    committeeDebatesDesc: (n: number): string => `${n} udvalgsbetænkninger planlagt til kammerdebat`,
    govProposals: 'Regeringsforslag',
    govProposalsDesc: (n: number): string => `${n} nye regeringsforslag under behandling`,
    weekAhead: 'Ugen fremover', committeeReportsTag: 'Udvalgsbetænkninger',
    govPropsTag: 'Regeringsforslag', oppMotionsTag: 'Oppositionsforslag', interpellationsTag: 'Interpellationsdebatter',
    // Enhanced summary labels
    committeeReport: 'udvalgsbetænkning',
    on: 'om',
    governmentProposition: 'Regeringsforslag',
    regarding: 'vedrørende',
    referredTo: 'henvist til',
    motionBy: 'Forslag fra',
    parliamentaryMotion: 'Parlamentarisk forslag',
    unknown: 'Ukendt',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `Sverigesrigsdagens udvalg har offentliggjort ${n} nye betænkninger, der afspejler igangværende lovgivningsarbejde.`,
    reportSignificance: 'Denne betænkning omhandler',
    readFullReport: 'Læs hele betænkningen',
    propsOverview: (n: number): string => `Regeringen har fremsat ${n} nye lovforslag til parlamentet.`,
    propSignificance: 'Dette forslag vedrører',
    readFullProp: 'Læs hele forslaget',
    motionsOverview: (n: number): string => `Oppositionsmedlemmer har indgivet ${n} nye forslag.`,
    motionSignificance: 'Dette forslag omhandler',
    readFullMotion: 'Læs hele forslaget',
    interpellationDefault: 'Parlamentarisk forespørgsel der kræver regeringens ansvarlighed.',
    readFullInterpellation: 'Læs hele interpellationen',
    policyContext: 'Politisk kontekst',
    filedBy: 'Indgivet af',
    published: 'Offentliggjort',
    politicalContext: 'Politisk kontekst',
    policyImplications: 'Politiske konsekvenser',
    keyTakeaways: 'Centrale konklusioner',
    thematicAnalysis: 'Tematisk analyse',
    legislativePipeline: 'Lovgivningsprocessen',
    oppositionStrategy: 'Oppositionens strategi',
    coalitionDynamics: 'Koalitionsdynamik',
    whatThisMeans: 'Hvad dette betyder',
    whyItMatters: 'Hvorfor det er vigtigt',
    committeeBreakdown: (n: number, c: number): string => `Denne omgang med ${n} udvalgsbetænkninger dækker ${c} forskellige udvalg.`,
    propsBreakdown: (n: number): string => `Regeringen har fremsat ${n} nye lovforslag.`,
    motionsBreakdown: (n: number): string => `Oppositionsmedlemmer har indgivet ${n} nye forslag.`,
    noInterpellations: 'Ingen interpellationer tilgængelige på nuværende tidspunkt.',
    interpellationsBreakdown: (n: number): string => `Oppositionsmedlemmer har indgivet ${n} interpellationer til ministre og kræver ansvarlighed og formelle svar om presserende politiske spørgsmål.`,
    debateDynamics: 'Debatdynamik og ansvarlighed',
    ministerAccountability: 'Rettet til',
    accountabilityAnalysis: 'Ansvarlighed',
    interpellationBy: 'Interpellation af',
    interpellationsScrutinyContext: (n: number): string => `Interpellationer fra ${n} forskellige partier viser en bred parlamentarisk granskning af regeringens ministre.`,
    interpellationsAccountabilityContext: (count: number, domains: number): string => `Disse ${count} interpellationer dækker ${domains} politikområde${domains > 1 ? 'r' : ''}, der afspejler bredden i parlamentariske ansvarlighedskrav til regeringen.`,
    committeeCountContext: (n: number): string => `${n} betænkninger fra dette udvalg signalerer intensivt lovgivningsarbejde.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `Parlamentets udvalg har været aktive inden for ${committees} og ${extra} yderligere politikområder.` : `Parlamentets udvalg har været aktive inden for ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `I alt ${n} betænkninger viser vedvarende lovgivningsmæssig fremdrift.`,
    oppositionStrategyContext: (n: number): string => `Forslag fra ${n} forskellige partier viser bredden i oppositionens politiske kritik.`,
    interpellationStrategyContext: (n: number): string => `Interpellationer fra ${n} forskellige partier viser koordineret parlamentarisk kontrol og krav om regeringsansvarlighed.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `Disse ${propCount} lovforslag berører ${domainCount} politikområde${domainCount > 1 ? 'r' : ''}, hvilket viser regeringens brede lovgivningsambition.`,
    genericOverview: (n: number): string => `I denne periode er ${n} dokumenter blevet behandlet i parlamentet.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} forslag indgivet`,
    partyInterpellationsFiled: (party: string, n: number): string => `${party}: ${n} interpellation${n > 1 ? 'er' : ''} indgivet`,
    otherCommittee: 'Andre udvalg',
    otherDocuments: 'Andre dokumenter',
    policySignificanceTouches: (domains: string): string => `Berører ${domains}.`,
    policySignificanceGeneric: 'Kræver udvalgsbehandling og kammerdebat, før der træffes afgørelse.',
    processedThisPeriod: 'behandlet i denne periode',
    generalMatters: 'Generelle spørgsmål',
    responsesToProp: 'Svar på regeringsforslag',
    independentMotions: 'Andre forslag',
    govEngagement: 'Regeringsdepartementernes engagement',
    twitterLabel1: 'Læsetid',
    twitterLabel2: 'Artikeltype',
    jobTitle: 'Politisk efterretningsanalytiker',
    siteDescription: 'Svensk parlamentsovervågning – følg politisk aktivitet med systematisk gennemsigtighed',
    deepAnalysis: 'Dybdeanalyse',
    deepAnalysisWho: 'Nøgleaktører',
    deepAnalysisWhat: 'Hvad der skete',
    deepAnalysisWhen: 'Tidslinje & kontekst',
    deepAnalysisWhy: 'Hvorfor det betyder noget',
    deepAnalysisWinners: 'Vindere & tabere',
    deepAnalysisImpact: 'Politisk indvirkning',
    deepAnalysisConsequences: 'Handlinger & konsekvenser',
    deepAnalysisCritical: 'Kritisk vurdering',
    deepAnalysisPerspectives: 'Flere perspektiver',
    swotAnalysis: 'SWOT-analyse',
    swotStrengths: 'Styrker',
    swotWeaknesses: 'Svagheder',
    swotOpportunities: 'Muligheder',
    swotThreats: 'Trusler',
    swotContext: 'Kontekst',
    swotImpactHigh: 'Høj',
    swotImpactMedium: 'Middel',
    swotImpactLow: 'Lav',
    dashboardTitle: 'Dashboard',
    dashboardSummary: 'Sammenfatning'
  },
  no: {
    whyMatters: 'Hvorfor denne uken er viktig',
    whyMattersDefault: 'Denne uken byr på viktig parlamentarisk aktivitet med sentrale debatter, komitémøter og regjeringskonsultasjoner.',
    keyEvents: 'Viktige hendelser denne uken',
    whatToWatch: 'Hva man bør følge med på',
    latestReports: 'Siste komitéinnstillinger',
    noReports: 'Ingen komitéinnstillinger tilgjengelige for øyeblikket.',
    committee: 'Komité', document: 'Dokument',
    reportDefault: 'Komitéinnstilling om parlamentarisk sak.',
    govProps: 'Regjeringens proposisjoner',
    noProps: 'Ingen regjeringsproposisjoner tilgjengelige for øyeblikket.',
    propDefault: 'Regjeringens forslag til parlamentet.',
    oppMotions: 'Opposisjonsforslag',
    noMotions: 'Ingen opposisjonsforslag tilgjengelige for øyeblikket.',
    author: 'Forfatter', party: 'Parti',
    motionDefault: 'Parlamentarisk forslag fra opposisjonsmedlem.',
    genericContent: 'Innholdsgenerering pågår.',
    monitorDev: 'Overvåk utviklingen og resultatene',
    committeeDebates: 'Komitédebatter',
    committeeDebatesDesc: (n: number): string => `${n} komitéinnstillinger planlagt for kammerdebatt`,
    govProposals: 'Regjeringsforslag',
    govProposalsDesc: (n: number): string => `${n} nye regjeringsproposisjoner under vurdering`,
    weekAhead: 'Uke fremover', committeeReportsTag: 'Komitéinnstillinger',
    govPropsTag: 'Regjeringens proposisjoner', oppMotionsTag: 'Opposisjonsforslag', interpellationsTag: 'Interpellasjonsdebatter',
    // Enhanced summary labels
    committeeReport: 'komitéinnstilling',
    on: 'om',
    governmentProposition: 'Regjeringens proposisjon',
    regarding: 'vedrørende',
    referredTo: 'henvist til',
    motionBy: 'Forslag fra',
    parliamentaryMotion: 'Parlamentarisk forslag',
    unknown: 'Ukjent',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `Den svenske riksdagens komiteer har publisert ${n} nye innstillinger som gjenspeiler pågående lovgivningsarbeid.`,
    reportSignificance: 'Denne innstillingen omhandler',
    readFullReport: 'Les hele innstillingen',
    propsOverview: (n: number): string => `Regjeringen har fremmet ${n} nye proposisjoner til Stortinget.`,
    propSignificance: 'Denne proposisjonen gjelder',
    readFullProp: 'Les hele proposisjonen',
    motionsOverview: (n: number): string => `Opposisjonsmedlemmer har fremmet ${n} nye forslag.`,
    motionSignificance: 'Dette forslaget omhandler',
    readFullMotion: 'Les hele forslaget',
    interpellationDefault: 'Parlamentarisk interpellasjon som krever regjeringens ansvarlighet.',
    readFullInterpellation: 'Les hele interpellasjonen',
    policyContext: 'Politisk kontekst',
    filedBy: 'Innsendt av',
    published: 'Publisert',
    politicalContext: 'Politisk kontekst',
    policyImplications: 'Politiske konsekvenser',
    keyTakeaways: 'Sentrale konklusjoner',
    thematicAnalysis: 'Tematisk analyse',
    legislativePipeline: 'Lovgivningsprosessen',
    oppositionStrategy: 'Opposisjonens strategi',
    coalitionDynamics: 'Koalisjonsdynamikk',
    whatThisMeans: 'Hva dette betyr',
    whyItMatters: 'Hvorfor det er viktig',
    committeeBreakdown: (n: number, c: number): string => `Denne runden med ${n} komitéinnstillinger dekker ${c} forskjellige komiteer.`,
    propsBreakdown: (n: number): string => `Regjeringen har fremmet ${n} nye proposisjoner.`,
    motionsBreakdown: (n: number): string => `Opposisjonsmedlemmer har innsendt ${n} nye forslag.`,
    noInterpellations: 'Ingen interpellasjoner tilgjengelige for øyeblikket.',
    interpellationsBreakdown: (n: number): string => `Opposisjonsmedlemmer har innsendt ${n} interpellasjoner til statsråder og krever ansvarlighet og formelle svar om presserende politiske spørsmål.`,
    debateDynamics: 'Debattdynamikk og ansvarlighet',
    ministerAccountability: 'Rettet til',
    accountabilityAnalysis: 'Ansvarlighetsanalyse',
    interpellationBy: 'Interpellasjon av',
    interpellationsScrutinyContext: (n: number): string => `Interpellasjoner fra ${n} ulike partier viser bred parlamentarisk gransking av regjeringens statsråder.`,
    interpellationsAccountabilityContext: (count: number, domains: number): string => `Disse ${count} interpellasjonene spenner over ${domains} politikkområde${domains > 1 ? 'r' : ''}, noe som gjenspeiler bredden i parlamentariske ansvarlighetskrav til regjeringen.`,
    committeeCountContext: (n: number): string => `${n} innstillinger fra denne komiteen signaliserer intensivt lovgivningsarbeid.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `Stortingets komiteer har vært aktive innen ${committees} og ${extra} ytterligere politikkområder.` : `Stortingets komiteer har vært aktive innen ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `Totalt ${n} innstillinger viser vedvarende lovgivende fremdrift.`,
    oppositionStrategyContext: (n: number): string => `Forslag fra ${n} ulike partier viser bredden i opposisjonens politiske kritikk.`,
    interpellationStrategyContext: (n: number): string => `Interpellasjoner fra ${n} ulike partier viser koordinert parlamentarisk kontroll og krav om regjeringsansvar.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `Disse ${propCount} proposisjonene berører ${domainCount} politikkområde${domainCount > 1 ? 'r' : ''}, og viser regjeringens brede lovgivningsambisjon.`,
    genericOverview: (n: number): string => `I denne perioden er ${n} dokumenter blitt behandlet i parlamentet.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} forslag innsendt`,
    partyInterpellationsFiled: (party: string, n: number): string => `${party}: ${n} interpellasjon${n > 1 ? 'er' : ''} innsendt`,
    otherCommittee: 'Andre komiteer',
    otherDocuments: 'Andre dokumenter',
    policySignificanceTouches: (domains: string): string => `Berører ${domains}.`,
    policySignificanceGeneric: 'Krever komitébehandling og kammerdebatt før avgjørelse fattes.',
    processedThisPeriod: 'behandlet denne perioden',
    generalMatters: 'Generelle spørsmål',
    responsesToProp: 'Svar på regjeringforslag',
    independentMotions: 'Andre forslag',
    govEngagement: 'Regjeringsdepartementenes engasjement',
    twitterLabel1: 'Lesetid',
    twitterLabel2: 'Artikkeltype',
    jobTitle: 'Politisk etterretningsanalytiker',
    siteDescription: 'Svensk parlamentsovervåkning – følg politisk aktivitet med systematisk åpenhet',
    deepAnalysis: 'Dybdeanalyse',
    deepAnalysisWho: 'Nøkkelaktører',
    deepAnalysisWhat: 'Hva som skjedde',
    deepAnalysisWhen: 'Tidslinje & kontekst',
    deepAnalysisWhy: 'Hvorfor det betyr noe',
    deepAnalysisWinners: 'Vinnere & tapere',
    deepAnalysisImpact: 'Politisk innvirkning',
    deepAnalysisConsequences: 'Handlinger & konsekvenser',
    deepAnalysisCritical: 'Kritisk vurdering',
    deepAnalysisPerspectives: 'Flere perspektiver',
    swotAnalysis: 'SWOT-analyse',
    swotStrengths: 'Styrker',
    swotWeaknesses: 'Svakheter',
    swotOpportunities: 'Muligheter',
    swotThreats: 'Trusler',
    swotContext: 'Kontekst',
    swotImpactHigh: 'Høy',
    swotImpactMedium: 'Middels',
    swotImpactLow: 'Lav',
    dashboardTitle: 'Dashbord',
    dashboardSummary: 'Sammendrag'
  },
  fi: {
    whyMatters: 'Miksi tämä viikko on tärkeä',
    whyMattersDefault: 'Tällä viikolla on merkittävää parlamentaarista toimintaa, johon kuuluu tärkeitä keskusteluja, valiokuntakokouksia ja hallituksen kuulemisia.',
    keyEvents: 'Viikon tärkeimmät tapahtumat',
    whatToWatch: 'Mitä seurata',
    latestReports: 'Uusimmat valiokuntamietinnöt',
    noReports: 'Ei valiokuntamietintöjä saatavilla tällä hetkellä.',
    committee: 'Valiokunta', document: 'Asiakirja',
    reportDefault: 'Valiokuntamietintö parlamentaarisesta asiasta.',
    govProps: 'Hallituksen esitykset',
    noProps: 'Ei hallituksen esityksiä saatavilla tällä hetkellä.',
    propDefault: 'Hallituksen esitys eduskunnalle.',
    oppMotions: 'Opposition aloitteet',
    noMotions: 'Ei opposition aloitteita saatavilla tällä hetkellä.',
    author: 'Tekijä', party: 'Puolue',
    motionDefault: 'Opposition jäsenen eduskunta-aloite.',
    genericContent: 'Sisältöä luodaan.',
    monitorDev: 'Seuraa kehitystä ja tuloksia',
    committeeDebates: 'Valiokuntakeskustelut',
    committeeDebatesDesc: (n: number): string => `${n} valiokuntamietintöä aikataulutettu täysistuntokeskusteluun`,
    govProposals: 'Hallituksen esitykset',
    govProposalsDesc: (n: number): string => `${n} uutta hallituksen esitystä käsittelyssä`,
    weekAhead: 'Tuleva viikko', committeeReportsTag: 'Valiokuntamietinnöt',
    govPropsTag: 'Hallituksen esitykset', oppMotionsTag: 'Opposition aloitteet', interpellationsTag: 'Välikysymyskeskustelut',
    // Enhanced summary labels
    committeeReport: 'valiokunnan mietintö',
    on: 'aiheesta',
    governmentProposition: 'Hallituksen esitys',
    regarding: 'koskien',
    referredTo: 'lähetetty valiokuntaan',
    motionBy: 'Aloite',
    parliamentaryMotion: 'Eduskunnan aloite',
    unknown: 'Tuntematon',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `Ruotsin valtiopäivien valiokunnat ovat julkaisseet ${n} uutta mietintöä, jotka heijastavat meneillään olevaa lainsäädäntötyötä.`,
    reportSignificance: 'Tämä mietintö käsittelee',
    readFullReport: 'Lue koko mietintö',
    propsOverview: (n: number): string => `Hallitus on jättänyt ${n} uutta esitystä eduskunnalle.`,
    propSignificance: 'Tämä esitys koskee',
    readFullProp: 'Lue koko esitys',
    motionsOverview: (n: number): string => `Opposition kansanedustajat ovat jättäneet ${n} uutta aloitetta.`,
    motionSignificance: 'Tämä aloite käsittelee',
    readFullMotion: 'Lue koko aloite',
    interpellationDefault: 'Hallituksen vastuuvelvollisuutta vaativa eduskunnan välikysymys.',
    readFullInterpellation: 'Lue koko välikysymys',
    policyContext: 'Poliittinen konteksti',
    filedBy: 'Jättänyt',
    published: 'Julkaistu',
    politicalContext: 'Poliittinen konteksti',
    policyImplications: 'Poliittiset vaikutukset',
    keyTakeaways: 'Keskeiset havainnot',
    thematicAnalysis: 'Temaattinen analyysi',
    legislativePipeline: 'Lainsäädäntöprosessi',
    oppositionStrategy: 'Opposition strategia',
    coalitionDynamics: 'Koalitiodynamiikka',
    whatThisMeans: 'Mitä tämä tarkoittaa',
    whyItMatters: 'Miksi tämä on tärkeää',
    committeeBreakdown: (n: number, c: number): string => `Tämä erä ${n} valiokunnan mietintöä kattaa ${c} eri valiokuntaa.`,
    propsBreakdown: (n: number): string => `Hallitus on jättänyt ${n} uutta esitystä.`,
    motionsBreakdown: (n: number): string => `Oppositiokansanedustajat ovat jättäneet ${n} uutta aloitetta.`,
    noInterpellations: 'Ei interpellaatioita saatavilla tällä hetkellä.',
    interpellationsBreakdown: (n: number): string => `Oppositiokansanedustajat ovat jättäneet ${n} interpellaatiota ministereille vaatien vastuullisuutta ja virallisia vastauksia kiireellisiin poliittisiin kysymyksiin.`,
    debateDynamics: 'Väittelyn dynamiikka ja vastuullisuus',
    ministerAccountability: 'Osoitettu',
    accountabilityAnalysis: 'Vastuullisuusanalyysi',
    interpellationBy: 'Välikysymys esittäjältä',
    interpellationsScrutinyContext: (n: number): string => `Välikysymykset ${n} eri puolueelta osoittavat laajaa parlamentaarista hallituksen ministereiden valvontaa.`,
    interpellationsAccountabilityContext: (count: number, domains: number): string => `Nämä ${count} välikysymystä kattavat ${domains} politiikka-aluetta, mikä heijastaa eduskunnan vastuullisuusvaatimusten laajuutta.`,
    committeeCountContext: (n: number): string => `${n} mietintöä tästä valiokunnasta osoittavat intensiivistä lainsäädäntötyötä.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `Eduskunnan valiokunnat ovat olleet aktiivisia aloilla ${committees} ja ${extra} muulla politiikka-alueella.` : `Eduskunnan valiokunnat ovat olleet aktiivisia aloilla ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `Yhteensä ${n} mietintöä osoittaa jatkuvaa lainsäädännöllistä vauhtia.`,
    oppositionStrategyContext: (n: number): string => `${n} eri puolueen aloitteet osoittavat opposition poliittisen kritiikin laajuuden.`,
    interpellationStrategyContext: (n: number): string => `${n} eri puolueen välikysymykset osoittavat koordinoitua parlamentaarista valvontaa ja vaatimuksia hallituksen vastuullisuudesta.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `Nämä ${propCount} esitystä koskevat ${domainCount} politiikka-aluetta, mikä osoittaa hallituksen laajaa lainsäädäntökunnianhimoa.`,
    genericOverview: (n: number): string => `Tänä aikana eduskunnassa käsiteltiin ${n} asiakirjaa.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} aloitetta jätetty`,
    partyInterpellationsFiled: (party: string, n: number): string => `${party}: ${n} välikysymy${n > 1 ? 'stä' : 's'} jätetty`,
    otherCommittee: 'Muut valiokunnat',
    otherDocuments: 'Muut asiakirjat',
    policySignificanceTouches: (domains: string): string => `Koskee aloja ${domains}.`,
    policySignificanceGeneric: 'Vaatii valiokuntakäsittelyn ja täysistuntokeskustelun ennen päätöksentekoa.',
    processedThisPeriod: 'käsitelty tällä kaudella',
    generalMatters: 'Yleiset asiat',
    responsesToProp: 'Vastaukset hallituksen esityksiin',
    independentMotions: 'Muut aloitteet',
    govEngagement: 'Ministeriöiden osallistuminen',
    twitterLabel1: 'Lukuaika',
    twitterLabel2: 'Artikkelityyppi',
    jobTitle: 'Poliittinen tiedusteluanalyytikko',
    siteDescription: 'Ruotsin parlamentin seuranta – poliittisen toiminnan systemaattinen läpinäkyvyys',
    deepAnalysis: 'Syväanalyysi',
    deepAnalysisWho: 'Keskeiset toimijat',
    deepAnalysisWhat: 'Mitä tapahtui',
    deepAnalysisWhen: 'Aikajana & konteksti',
    deepAnalysisWhy: 'Miksi tällä on merkitystä',
    deepAnalysisWinners: 'Voittajat & häviäjät',
    deepAnalysisImpact: 'Poliittinen vaikutus',
    deepAnalysisConsequences: 'Toimet & seuraukset',
    deepAnalysisCritical: 'Kriittinen arvio',
    deepAnalysisPerspectives: 'Useat näkökulmat',
    swotAnalysis: 'SWOT-analyysi',
    swotStrengths: 'Vahvuudet',
    swotWeaknesses: 'Heikkoudet',
    swotOpportunities: 'Mahdollisuudet',
    swotThreats: 'Uhat',
    swotContext: 'Konteksti',
    swotImpactHigh: 'Korkea',
    swotImpactMedium: 'Keskitaso',
    swotImpactLow: 'Matala',
    dashboardTitle: 'Kojelauta',
    dashboardSummary: 'Yhteenveto'
  },
  de: {
    whyMatters: 'Warum diese Woche wichtig ist',
    whyMattersDefault: 'Diese Woche bietet bedeutende parlamentarische Aktivitäten mit wichtigen Debatten, Ausschusssitzungen und Regierungskonsultationen.',
    keyEvents: 'Wichtige Ereignisse diese Woche',
    whatToWatch: 'Was zu beobachten ist',
    latestReports: 'Neueste Ausschussberichte',
    noReports: 'Derzeit keine Ausschussberichte verfügbar.',
    committee: 'Ausschuss', document: 'Dokument',
    reportDefault: 'Ausschussbericht über parlamentarische Angelegenheit.',
    govProps: 'Regierungsvorlagen',
    noProps: 'Derzeit keine Regierungsvorlagen verfügbar.',
    propDefault: 'Regierungsvorlage an das Parlament.',
    oppMotions: 'Oppositionsanträge',
    noMotions: 'Derzeit keine Oppositionsanträge verfügbar.',
    author: 'Autor', party: 'Partei',
    motionDefault: 'Parlamentarischer Antrag eines Oppositionsmitglieds.',
    genericContent: 'Inhaltserstellung läuft.',
    monitorDev: 'Entwicklungen und Ergebnisse überwachen',
    committeeDebates: 'Ausschussdebatten',
    committeeDebatesDesc: (n: number): string => `${n} Ausschussberichte für Plenardebatte geplant`,
    govProposals: 'Regierungsvorlagen',
    govProposalsDesc: (n: number): string => `${n} neue Regierungsvorlagen in Prüfung`,
    weekAhead: 'Woche Voraus', committeeReportsTag: 'Ausschussberichte',
    govPropsTag: 'Regierungsvorlagen', oppMotionsTag: 'Oppositionsanträge', interpellationsTag: 'Interpellationsdebatten',
    // Enhanced summary labels
    committeeReport: 'Ausschussbericht',
    on: 'über',
    governmentProposition: 'Regierungsvorlage',
    regarding: 'bezüglich',
    referredTo: 'verwiesen an',
    motionBy: 'Antrag von',
    parliamentaryMotion: 'Parlamentarischer Antrag',
    unknown: 'Unbekannt',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `Die Ausschüsse des schwedischen Reichstags haben ${n} neue Berichte veröffentlicht, die laufende Gesetzgebungsarbeit widerspiegeln.`,
    reportSignificance: 'Dieser Bericht befasst sich mit',
    readFullReport: 'Den vollständigen Bericht lesen',
    propsOverview: (n: number): string => `Die Regierung hat ${n} neue Vorlagen an das Parlament übermittelt.`,
    propSignificance: 'Diese Vorlage betrifft',
    readFullProp: 'Die vollständige Vorlage lesen',
    motionsOverview: (n: number): string => `Oppositionsabgeordnete haben ${n} neue Anträge eingereicht.`,
    motionSignificance: 'Dieser Antrag befasst sich mit',
    readFullMotion: 'Den vollständigen Antrag lesen',
    interpellationDefault: 'Parlamentarische Interpellation, die Rechenschaft der Regierung verlangt.',
    readFullInterpellation: 'Die vollständige Interpellation lesen',
    policyContext: 'Politischer Kontext',
    filedBy: 'Eingereicht von',
    published: 'Veröffentlicht',
    politicalContext: 'Politischer Kontext',
    policyImplications: 'Politische Auswirkungen',
    keyTakeaways: 'Zentrale Erkenntnisse',
    thematicAnalysis: 'Thematische Analyse',
    legislativePipeline: 'Gesetzgebungsverfahren',
    oppositionStrategy: 'Oppositionsstrategie',
    coalitionDynamics: 'Koalitionsdynamik',
    whatThisMeans: 'Was dies bedeutet',
    whyItMatters: 'Warum es wichtig ist',
    committeeBreakdown: (n: number, c: number): string => `Diese Runde von ${n} Ausschussberichten umfasst ${c} verschiedene Ausschüsse.`,
    propsBreakdown: (n: number): string => `Die Regierung hat ${n} neue Vorlagen eingebracht.`,
    motionsBreakdown: (n: number): string => `Oppositionsabgeordnete haben ${n} neue Anträge eingereicht.`,
    noInterpellations: 'Derzeit keine Interpellationen verfügbar.',
    interpellationsBreakdown: (n: number): string => `Oppositionsabgeordnete haben ${n} Interpellationen an Regierungsminister eingereicht und fordern Rechenschaft sowie formelle Antworten zu drängenden politischen Fragen.`,
    debateDynamics: 'Debattendynamik und Verantwortlichkeit',
    ministerAccountability: 'Gerichtet an',
    accountabilityAnalysis: 'Verantwortlichkeitsanalyse',
    interpellationBy: 'Interpellation von',
    interpellationsScrutinyContext: (n: number): string => `Interpellationen aus ${n} verschiedenen Parteien zeigen eine breite parlamentarische Kontrolle der Regierungsminister.`,
    interpellationsAccountabilityContext: (count: number, domains: number): string => `Diese ${count} Interpellationen erstrecken sich über ${domains} Politikbereich${domains > 1 ? 'e' : ''}, was die Breite der parlamentarischen Rechenschaftsforderungen an die Regierung widerspiegelt.`,
    committeeCountContext: (n: number): string => `${n} Berichte dieses Ausschusses signalisieren intensive Gesetzgebungsarbeit.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `Die Parlamentsausschüsse waren in den Bereichen ${committees} und ${extra} weiteren Politikfeldern aktiv.` : `Die Parlamentsausschüsse waren in den Bereichen ${committees} aktiv.`,
    committeeMomentumTakeaway: (n: number): string => `Insgesamt ${n} Berichte zeugen von anhaltendem Gesetzgebungsmomentum.`,
    oppositionStrategyContext: (n: number): string => `Anträge aus ${n} verschiedenen Parteien zeigen die Breite der oppositionellen politischen Kritik.`,
    interpellationStrategyContext: (n: number): string => `Interpellationen aus ${n} verschiedenen Parteien zeigen koordinierte parlamentarische Kontrolle und Forderungen nach Regierungsverantwortung.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `Diese ${propCount} Vorlagen betreffen ${domainCount} Politikbereich${domainCount > 1 ? 'e' : ''} und demonstrieren den breiten Gesetzgebungsanspruch der Regierung.`,
    genericOverview: (n: number): string => `In diesem Zeitraum wurden ${n} Dokumente im Parlament behandelt.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} Antrag${n > 1 ? 'e' : ''} eingereicht`,
    partyInterpellationsFiled: (party: string, n: number): string => `${party}: ${n} Interpellation${n > 1 ? 'en' : ''} eingereicht`,
    otherCommittee: 'Sonstige Ausschüsse',
    otherDocuments: 'Sonstige Dokumente',
    policySignificanceTouches: (domains: string): string => `Betrifft ${domains}.`,
    policySignificanceGeneric: 'Erfordert Ausschussberatung und Kammerdebatte vor einer Entscheidung.',
    processedThisPeriod: 'in dieser Periode behandelt',
    generalMatters: 'Allgemeine Angelegenheiten',
    responsesToProp: 'Antworten auf Regierungsvorlagen',
    independentMotions: 'Sonstige Anträge',
    govEngagement: 'Engagement der Regierungsressorts',
    twitterLabel1: 'Lesezeit',
    twitterLabel2: 'Artikeltyp',
    jobTitle: 'Politischer Geheimdienstanalyst',
    siteDescription: 'Schwedische Parlamentsplattform – politische Aktivität mit systematischer Transparenz verfolgen',
    deepAnalysis: 'Tiefenanalyse',
    deepAnalysisWho: 'Schlüsselakteure',
    deepAnalysisWhat: 'Was geschah',
    deepAnalysisWhen: 'Zeitstrahl & Kontext',
    deepAnalysisWhy: 'Warum es wichtig ist',
    deepAnalysisWinners: 'Gewinner & Verlierer',
    deepAnalysisImpact: 'Politische Auswirkung',
    deepAnalysisConsequences: 'Handlungen & Konsequenzen',
    deepAnalysisCritical: 'Kritische Bewertung',
    deepAnalysisPerspectives: 'Mehrere Perspektiven',
    swotAnalysis: 'SWOT-Analyse',
    swotStrengths: 'Stärken',
    swotWeaknesses: 'Schwächen',
    swotOpportunities: 'Chancen',
    swotThreats: 'Risiken',
    swotContext: 'Kontext',
    swotImpactHigh: 'Hoch',
    swotImpactMedium: 'Mittel',
    swotImpactLow: 'Niedrig',
    dashboardTitle: 'Dashboard',
    dashboardSummary: 'Zusammenfassung'
  },
  fr: {
    whyMatters: 'Pourquoi cette semaine est importante',
    whyMattersDefault: 'Cette semaine est marquée par une activité parlementaire significative avec des débats clés, des réunions de commission et des consultations gouvernementales.',
    keyEvents: 'Événements clés cette semaine',
    whatToWatch: 'À suivre',
    latestReports: 'Derniers rapports de commission',
    noReports: 'Aucun rapport de commission disponible pour le moment.',
    committee: 'Commission', document: 'Document',
    reportDefault: 'Rapport de commission sur une affaire parlementaire.',
    govProps: 'Propositions gouvernementales',
    noProps: 'Aucune proposition gouvernementale disponible pour le moment.',
    propDefault: 'Proposition du gouvernement au Parlement.',
    oppMotions: 'Motions d\'opposition',
    noMotions: 'Aucune motion d\'opposition disponible pour le moment.',
    author: 'Auteur', party: 'Parti',
    motionDefault: 'Motion parlementaire d\'un membre de l\'opposition.',
    genericContent: 'Génération de contenu en cours.',
    monitorDev: 'Suivre les développements et les résultats',
    committeeDebates: 'Débats en commission',
    committeeDebatesDesc: (n: number): string => `${n} rapports de commission prévus pour débat en séance`,
    govProposals: 'Propositions gouvernementales',
    govProposalsDesc: (n: number): string => `${n} nouvelles propositions gouvernementales à l'examen`,
    weekAhead: 'Semaine à venir', committeeReportsTag: 'Rapports de commission',
    govPropsTag: 'Propositions gouvernementales', oppMotionsTag: 'Motions d\'opposition', interpellationsTag: 'Débats d\'interpellation',
    // Enhanced summary labels
    committeeReport: 'rapport de commission',
    on: 'sur',
    governmentProposition: 'Proposition gouvernementale',
    regarding: 'concernant',
    referredTo: 'renvoyée à',
    motionBy: 'Motion de',
    parliamentaryMotion: 'Motion parlementaire',
    unknown: 'Inconnu',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `Les commissions du Riksdag suédois ont publié ${n} nouveaux rapports reflétant le travail législatif en cours.`,
    reportSignificance: 'Ce rapport traite de',
    readFullReport: 'Lire le rapport complet',
    propsOverview: (n: number): string => `Le gouvernement a soumis ${n} nouvelles propositions au Parlement.`,
    propSignificance: 'Cette proposition concerne',
    readFullProp: 'Lire la proposition complète',
    motionsOverview: (n: number): string => `Des députés de l'opposition ont déposé ${n} nouvelles motions.`,
    motionSignificance: 'Cette motion traite de',
    readFullMotion: 'Lire la motion complète',
    interpellationDefault: 'Interpellation parlementaire exigeant la responsabilité du gouvernement.',
    readFullInterpellation: 'Lire l\'interpellation complète',
    policyContext: 'Contexte politique',
    filedBy: 'Déposé par',
    published: 'Publié',
    politicalContext: 'Contexte politique',
    policyImplications: 'Implications politiques',
    keyTakeaways: 'Points clés',
    thematicAnalysis: 'Analyse thématique',
    legislativePipeline: 'Processus législatif',
    oppositionStrategy: 'Stratégie de l\'opposition',
    coalitionDynamics: 'Dynamique de coalition',
    whatThisMeans: 'Ce que cela signifie',
    whyItMatters: 'Pourquoi c\'est important',
    committeeBreakdown: (n: number, c: number): string => `Ce lot de ${n} rapports de commission couvre ${c} commissions différentes.`,
    propsBreakdown: (n: number): string => `Le gouvernement a soumis ${n} nouvelles propositions.`,
    motionsBreakdown: (n: number): string => `Les députés de l'opposition ont déposé ${n} nouvelles motions.`,
    noInterpellations: 'Aucune interpellation disponible pour le moment.',
    interpellationsBreakdown: (n: number): string => `Les députés de l'opposition ont déposé ${n} interpellations auprès des ministres du gouvernement, exigeant des comptes et des réponses formelles sur des questions politiques urgentes.`,
    debateDynamics: 'Dynamique du débat et responsabilité',
    ministerAccountability: 'Adressée à',
    accountabilityAnalysis: 'Analyse de la responsabilité',
    interpellationBy: 'Interpellation par',
    interpellationsScrutinyContext: (n: number): string => `Des interpellations de ${n} partis différents démontrent un large contrôle parlementaire des ministres du gouvernement.`,
    interpellationsAccountabilityContext: (count: number, domains: number): string => `Ces ${count} interpellations couvrent ${domains} domaine${domains > 1 ? 's' : ''} politique${domains > 1 ? 's' : ''}, reflétant l'ampleur des exigences de responsabilité parlementaire envers le gouvernement.`,
    committeeCountContext: (n: number): string => `${n} rapports de cette commission témoignent d'un travail législatif intensif.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `Les commissions parlementaires ont été actives dans les domaines ${committees} et ${extra} autres domaines politiques.` : `Les commissions parlementaires ont été actives dans les domaines ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `Un total de ${n} rapports démontre un élan législatif soutenu.`,
    oppositionStrategyContext: (n: number): string => `Des motions de ${n} partis différents révèlent l'étendue de la critique politique de l'opposition.`,
    interpellationStrategyContext: (n: number): string => `Des interpellations de ${n} partis différents démontrent un contrôle parlementaire coordonné et des exigences de responsabilité gouvernementale.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `Ces ${propCount} propositions touchent à ${domainCount} domaine${domainCount > 1 ? 's' : ''} politique${domainCount > 1 ? 's' : ''}, démontrant l'ambition législative du gouvernement.`,
    genericOverview: (n: number): string => `Durant cette période, ${n} documents ont été traités au parlement.`,
    partyMotionsFiled: (party: string, n: number): string => `${party} : ${n} motion${n > 1 ? 's' : ''} déposée${n > 1 ? 's' : ''}`,
    partyInterpellationsFiled: (party: string, n: number): string => `${party} : ${n} interpellation${n > 1 ? 's' : ''} déposée${n > 1 ? 's' : ''}`,
    otherCommittee: 'Autres commissions',
    otherDocuments: 'Autres documents',
    policySignificanceTouches: (domains: string): string => `Touche aux domaines ${domains}.`,
    policySignificanceGeneric: 'Nécessite un examen en commission et un débat en séance avant toute décision.',
    processedThisPeriod: 'traités au cours de cette période',
    generalMatters: 'Questions générales',
    responsesToProp: 'Réponses aux propositions gouvernementales',
    independentMotions: 'Autres motions',
    govEngagement: 'Engagement des ministères',
    twitterLabel1: 'Temps de lecture',
    twitterLabel2: "Type d'article",
    jobTitle: 'Analyste en renseignement politique',
    siteDescription: "Plateforme du Parlement suédois – surveiller l'activité politique avec une transparence systématique",
    deepAnalysis: 'Analyse approfondie',
    deepAnalysisWho: 'Acteurs clés',
    deepAnalysisWhat: 'Ce qui s\'est passé',
    deepAnalysisWhen: 'Chronologie & contexte',
    deepAnalysisWhy: 'Pourquoi c\'est important',
    deepAnalysisWinners: 'Gagnants & perdants',
    deepAnalysisImpact: 'Impact politique',
    deepAnalysisConsequences: 'Actions & conséquences',
    deepAnalysisCritical: 'Évaluation critique',
    deepAnalysisPerspectives: 'Perspectives multiples',
    swotAnalysis: 'Analyse SWOT',
    swotStrengths: 'Forces',
    swotWeaknesses: 'Faiblesses',
    swotOpportunities: 'Opportunités',
    swotThreats: 'Menaces',
    swotContext: 'Contexte',
    swotImpactHigh: 'Élevé',
    swotImpactMedium: 'Moyen',
    swotImpactLow: 'Faible',
    dashboardTitle: 'Tableau de bord',
    dashboardSummary: 'Résumé'
  },
};
