/**
 * @module data-transformers/content-generators
 * @description Barrel re-export for all per-article-type content generators.
 * The monolithic content-generators.ts has been decomposed into focused modules:
 * - **shared** — internal helpers (TITLE_SUFFIX_TEMPLATES, extractKeywords, …)
 * - **week-ahead** — generateWeekAheadContent
 * - **committee** — generateCommitteeContent
 * - **propositions** — generatePropositionsContent
 * - **motions** — generateMotionsContent
 * - **interpellations** — generateInterpellationsContent (dedicated, separate from motions)
 * - **generic** — generateGenericContent
 * - **monthly-review** — generateMonthlyReviewContent
 * - **month-ahead** — generateMonthAheadContent
 * - **swot-section** — generateSwotSection  (embeddable SWOT analysis)
 * - **dashboard-section** — generateDashboardSection  (embeddable Chart.js dashboard)
 * - **stakeholder-swot-section** — generateStakeholderSwotSection  (multi-stakeholder SWOT)
 * - **economic-dashboard-section** — generateEconomicDashboardSection  (World Bank dashboards)
 * - **sankey-section** — generateSankeySection  (inline SVG Sankey flow charts)
 * - **mindmap-section** — generateMindmapSection  (color-coded CSS mindmaps)
 * - **newsworthiness** — scoreNewsworthiness  (multi-dimensional news value scoring)
 * - **cia-overview-section** — generateCiaOverviewSection  (CIA parliamentary intelligence overview)
 *
 * @author Hack23 AB
 * @license Apache-2.0
 */

export { generateWeekAheadContent } from './week-ahead.js';
export { generateCommitteeContent } from './committee.js';
export { generatePropositionsContent } from './propositions.js';
export { generateMotionsContent } from './motions.js';
export { generateInterpellationsContent } from './interpellations.js';
export { generateGenericContent } from './generic.js';
export { generateMonthlyReviewContent } from './monthly-review.js';
export { generateMonthAheadContent } from './month-ahead.js';
export { generateDeepAnalysisSection, localizeDocType, DOC_TYPE_DISPLAY, analyzeDocumentsForContent } from './shared.js';
export type { DeepAnalysisOptions, DocTypeLocalization } from './shared.js';
export { generateSwotSection } from './swot-section.js';
export type { SwotSectionOptions } from './swot-section.js';
export { generateDashboardSection, generateMultiPanelDashboardSection } from './dashboard-section.js';
export type { DashboardSectionOptions, MultiPanelDashboardOptions } from './dashboard-section.js';
export { generateEconomicDashboardSection, findIndicatorsForDomains, buildEconomicCharts, buildEconomicTables } from './economic-dashboard-section.js';
export type { EconomicDashboardOptions, EconomicDataPoint } from './economic-dashboard-section.js';
export { scoreNewsworthiness } from './newsworthiness.js';
export type { NewsworthinessScore, NewsworthinessDimension } from './newsworthiness.js';
export { generateMindmapSection } from './mindmap-section.js';
export type { MindmapSectionOptions, MindmapBranch, MindmapBranchColor, MindmapDimension, AIMindmapItem, AIMindmapItemWeight, SubBranch, MindmapConnection } from './mindmap-section.js';
export { buildAIMindmapAnalysis, buildMindmapOptionsFromAnalysis } from './ai-mindmap-analyzer.js';
export type { AIMindmapAnalysis } from './ai-mindmap-analyzer.js';
export { generateSankeySection } from './sankey-section.js';
export type { SankeySectionOptions, SankeyNode, SankeyFlow, SankeyNodeColor } from './sankey-section.js';
export { generateCiaOverviewSection } from './cia-overview-section.js';
export type { CiaOverviewSectionOptions } from './cia-overview-section.js';

// ---------------------------------------------------------------------------
// Stubs for deleted stakeholder-swot-section module.
// The stakeholder SWOT is now generated by the AI agent in agentic workflows
// (Rule 2). These stubs keep barrel re-exports intact.
// ---------------------------------------------------------------------------

import type { Language } from '../../types/language.js';
import type { TemplateSection } from '../../types/article.js';

/** Options for the stakeholder SWOT section generator */
export interface StakeholderSwotSectionOptions {
  stakeholders: StakeholderSwot[];
  lang: Language;
  strategicContext?: string;
}

/** A single stakeholder's SWOT analysis */
export interface StakeholderSwot {
  name: string;
  role?: string;
  category?: string;
  swot: { strengths: Array<{ text: string }>; weaknesses: Array<{ text: string }>; opportunities: Array<{ text: string }>; threats: Array<{ text: string }> };
  evidenceRefs?: string[];
  confidenceLevel?: 'high' | 'medium' | 'low';
}

/** Stub: returns an empty section. Real content is AI-generated in workflows. */
export function generateStakeholderSwotSection(_options: StakeholderSwotSectionOptions): TemplateSection {
  return { id: 'stakeholder-swot', html: '' };
}
