# Analyze only source code
sonar.sources=src,scripts

# Analyze only tests
sonar.tests=tests

# Source encoding
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
docs,\
analysis,\
data,\
images,\
dist,\
build
