/**
 * Regression guard: every directory of static HTML pages produced by
 * the prebuild scripts MUST be wired into vite.config.js's
 * `staticPagesPlugin({ pageSets })` so they end up in `dist/` and are
 * served by `vite preview` (and therefore reachable from Cypress).
 *
 * Root cause for run 25549240331 (1 passing / 20 failing in
 * cypress/e2e/dashboards.cy.js): the 9 specialised dashboard pages
 * generated by `scripts/build-dashboard-pages.py` into `dashboards/`
 * (×14 languages = 126 files) were never copied into `dist/`, so
 * `vite preview` returned 404 for `/dashboards/parties.html` etc.
 *
 * This test reads `vite.config.js` as text and asserts the page sets
 * we depend on are present. It is intentionally a string-match check
 * — full execution of the Vite config would require pulling in the
 * entire build graph, which is out of scope for a unit test.
 *
 * @author Hack23 AB
 * @license Apache-2.0
 */

import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

const VITE_CONFIG = fs.readFileSync(
  path.join(__dirname, '..', 'vite.config.js'),
  'utf8',
);

describe('vite.config.js — staticPagesPlugin pageSets', () => {
  it('registers the news-articles page set (recurse: true)', () => {
    expect(VITE_CONFIG).toMatch(/label:\s*['"]news-articles['"]/);
    expect(VITE_CONFIG).toMatch(
      /label:\s*['"]news-articles['"][\s\S]{0,200}path:\s*['"]news['"][\s\S]{0,40}recurse:\s*true/,
    );
  });

  it('registers the sitemaps page set with all 14 language variants', () => {
    expect(VITE_CONFIG).toMatch(/label:\s*['"]sitemaps['"]/);
    for (const lang of [
      'sv', 'da', 'no', 'fi', 'de', 'fr', 'es',
      'nl', 'ar', 'he', 'ja', 'ko', 'zh',
    ]) {
      expect(VITE_CONFIG).toMatch(
        new RegExp(`path:\\s*['"]sitemap_${lang}\\.html['"]`),
      );
    }
    expect(VITE_CONFIG).toMatch(/path:\s*['"]sitemap\.html['"]/);
  });

  it('registers the political-intelligence page set with all 14 language variants', () => {
    expect(VITE_CONFIG).toMatch(/label:\s*['"]political-intelligence['"]/);
    for (const lang of [
      'sv', 'da', 'no', 'fi', 'de', 'fr', 'es',
      'nl', 'ar', 'he', 'ja', 'ko', 'zh',
    ]) {
      expect(VITE_CONFIG).toMatch(
        new RegExp(`path:\\s*['"]political-intelligence_${lang}\\.html['"]`),
      );
    }
    expect(VITE_CONFIG).toMatch(/path:\s*['"]political-intelligence\.html['"]/);
  });

  it('registers the dashboards page set so /dashboards/*.html is served by vite preview', () => {
    // Failure to register this set is the root cause of every Cypress
    // assertion in cypress/e2e/dashboards.cy.js missing — see header
    // comment for the regression context.
    expect(VITE_CONFIG).toMatch(/label:\s*['"]dashboards['"]/);
    expect(VITE_CONFIG).toMatch(
      /label:\s*['"]dashboards['"][\s\S]{0,400}path:\s*['"]dashboards['"]/,
    );
  });

  it('every directory listed in build-dashboard-pages.py output exists on disk', () => {
    // The 9 slugs the build script produces, sanity-check that each
    // landed on disk under dashboards/. If this fails, regenerate via
    // `python3 scripts/build-dashboard-pages.py`.
    const slugs = [
      'parties',
      'anomaly-detection',
      'coalitions',
      'committees',
      'election-cycle',
      'ministers',
      'pre-election',
      'risk',
      'seasonal-patterns',
    ];
    const root = path.join(__dirname, '..', 'dashboards');
    for (const slug of slugs) {
      const en = path.join(root, `${slug}.html`);
      expect(
        fs.existsSync(en),
        `Missing dashboards/${slug}.html — regenerate with build-dashboard-pages.py`,
      ).toBe(true);
    }
  });
});
