/**
 * @module fix-committee-reports-body
 * @description Fixes committee reports articles for 2026-02-16, 2026-02-17, 2026-02-18,
 * and 2026-02-24 that have English body content in non-English language versions.
 *
 * The lede paragraph and article-meta are already correctly translated.
 * This script replaces the English body sections (h2/h3 headings and paragraphs)
 * with content generated by the multilingual generateCommitteeContent function.
 *
 * Usage: npx tsx scripts/fix-committee-reports-body.ts
 *
 * @author Hack23 AB
 * @license Apache-2.0
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { generateArticleContent } from './data-transformers.js';
import type { ArticleContentData } from './data-transformers.js';
import { generateWatchSection } from './article-template.js';
import type { Language } from './types/language.js';
import type { RawDocument } from './data-transformers/types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const NEWS_DIR = path.join(__dirname, '..', 'news');

const NON_ENGLISH_LANGS: Language[] = ['sv', 'da', 'no', 'fi', 'de', 'fr', 'es', 'nl', 'ar', 'he', 'ja', 'ko', 'zh'];

// ---------------------------------------------------------------------------
// Committee report data for 2026-02-16, 2026-02-17, 2026-02-18 (same reports)
// ---------------------------------------------------------------------------
const REPORTS_2026_02_18: RawDocument[] = [
  {
    organ: 'FiU',
    title: 'Supplementary Appropriations Bill – Support for Ukraine and Vaccine Preparedness',
    dok_id: 'HD01FiU46',
    dokumentnamn: 'HD01FiU46',
    url: 'https://data.riksdagen.se/dokument/HD01FiU46.html',
    doktyp: 'bet',
    summary: 'Tilläggsbudget med stöd till Ukraina och förstärkt vaccinberedskap.',
  },
  {
    organ: 'SkU',
    title: 'Future Data Protection at the Swedish Tax Agency, Customs, and Enforcement Authority',
    dok_id: 'HD01SkU10',
    dokumentnamn: 'HD01SkU10',
    url: 'https://data.riksdagen.se/dokument/HD01SkU10.html',
    doktyp: 'bet',
    summary: 'Framtida dataskydd vid Skatteverket, Tullverket och Kronofogdemyndigheten.',
  },
  {
    organ: 'SkU',
    title: 'Controls on Cash at Internal Borders',
    dok_id: 'HD01SkU19',
    dokumentnamn: 'HD01SkU19',
    url: 'https://data.riksdagen.se/dokument/HD01SkU19.html',
    doktyp: 'bet',
    summary: 'Kontroller av kontanta medel vid den inre gränsen.',
  },
  {
    organ: 'SfU',
    title: 'Abolition of the Notification Requirement Before Applying for Parental Benefit',
    dok_id: 'HD01SfU20',
    dokumentnamn: 'HD01SfU20',
    url: 'https://data.riksdagen.se/dokument/HD01SfU20.html',
    doktyp: 'bet',
    summary: 'Avskaffande av anmälningskravet innan ansökan om föräldrapenning.',
  },
  {
    organ: 'SoU',
    title: 'Better Conditions for Deploying Government Personnel Abroad',
    dok_id: 'HD01SoU36',
    dokumentnamn: 'HD01SoU36',
    url: 'https://data.riksdagen.se/dokument/HD01SoU36.html',
    doktyp: 'bet',
    summary: 'Bättre förutsättningar att sända ut statlig personal utomlands.',
  },
  {
    organ: 'CU',
    title: 'A Registry for All Housing Cooperatives',
    dok_id: 'HD01CU28',
    dokumentnamn: 'HD01CU28',
    url: 'https://data.riksdagen.se/dokument/HD01CU28.html',
    doktyp: 'bet',
    summary: 'Ett register för alla bostadsrätter.',
  },
  {
    organ: 'TU',
    title: 'Road Traffic and Vehicle Issues',
    dok_id: 'HD01TU9',
    dokumentnamn: 'HD01TU9',
    url: 'https://data.riksdagen.se/dokument/HD01TU9.html',
    doktyp: 'bet',
    summary: 'Vägtrafik- och fordonsfrågor.',
  },
  {
    organ: 'MJU',
    title: 'Animal Protection',
    dok_id: 'HD01MJU9',
    dokumentnamn: 'HD01MJU9',
    url: 'https://data.riksdagen.se/dokument/HD01MJU9.html',
    doktyp: 'bet',
    summary: 'Djurskyddsfrågor.',
  },
  {
    organ: 'NU',
    title: 'Trade Policy',
    dok_id: 'HD01NU11',
    dokumentnamn: 'HD01NU11',
    url: 'https://data.riksdagen.se/dokument/HD01NU11.html',
    doktyp: 'bet',
    summary: 'Handelspolitik och internationella handelsrelationer.',
  },
  {
    organ: 'UbU',
    title: 'Fundamentals of Education',
    dok_id: 'HD01UbU8',
    dokumentnamn: 'HD01UbU8',
    url: 'https://data.riksdagen.se/dokument/HD01UbU8.html',
    doktyp: 'bet',
    summary: 'Grundläggande om utbildning och skolfrågor.',
  },
];

// ---------------------------------------------------------------------------
// Committee report data for 2026-02-24 (different reports)
// ---------------------------------------------------------------------------
const REPORTS_2026_02_24: RawDocument[] = [
  // Energy/Industry (NU) – 6 reports
  {
    organ: 'NU',
    title: 'Wind Power in Municipalities',
    dok_id: 'HD01NU20',
    dokumentnamn: 'HD01NU20',
    url: 'https://data.riksdagen.se/dokument/HD01NU20',
    doktyp: 'bet',
    summary: 'Vindkraft i kommuner och kommunalt veto.',
  },
  {
    organ: 'NU',
    title: 'More Efficient Review of Nuclear Facilities',
    dok_id: 'HD01NU19',
    dokumentnamn: 'HD01NU19',
    url: 'https://data.riksdagen.se/dokument/HD01NU19',
    doktyp: 'bet',
    summary: 'Effektivare prövning av kärntekniska anläggningar.',
  },
  {
    organ: 'NU',
    title: 'Licensing Under the Renewables Directive',
    dok_id: 'HD01NU18',
    dokumentnamn: 'HD01NU18',
    url: 'https://data.riksdagen.se/dokument/HD01NU18',
    doktyp: 'bet',
    summary: 'Tillstånd enligt förnybartdirektivet.',
  },
  {
    organ: 'NU',
    title: 'Safety and Radiation Protection Requirements for Nuclear Fuel Processing',
    dok_id: 'HD01NU27',
    dokumentnamn: 'HD01NU27',
    url: 'https://data.riksdagen.se/dokument/HD01NU27',
    doktyp: 'bet',
    summary: 'Säkerhets- och strålskyddskrav vid hantering av kärnbränsle.',
  },
  {
    organ: 'NU',
    title: 'New Laws on the Electricity System',
    dok_id: 'HD01NU25',
    dokumentnamn: 'HD01NU25',
    url: 'https://data.riksdagen.se/dokument/HD01NU25',
    doktyp: 'bet',
    summary: 'Ny lagstiftning om elsystemet.',
  },
  {
    organ: 'NU',
    title: 'New Nuclear Power in Sweden — More Possible Coastal Sites',
    dok_id: 'HD01NU24',
    dokumentnamn: 'HD01NU24',
    url: 'https://data.riksdagen.se/dokument/HD01NU24',
    doktyp: 'bet',
    summary: 'Ny kärnkraft i Sverige – fler möjliga kustplatser.',
  },
  // Social Insurance (SfU) – 12 reports
  {
    organ: 'SfU',
    title: 'Qualification for Social Insurance',
    dok_id: 'HD01SfU21',
    dokumentnamn: 'HD01SfU21',
    url: 'https://data.riksdagen.se/dokument/HD01SfU21',
    doktyp: 'bet',
    summary: 'Kvalificering för socialförsäkring.',
  },
  {
    organ: 'SfU',
    title: 'Better Migration Rules for Researchers and Doctoral Students',
    dok_id: 'HD01SfU23',
    dokumentnamn: 'HD01SfU23',
    url: 'https://data.riksdagen.se/dokument/HD01SfU23',
    doktyp: 'bet',
    summary: 'Bättre migrationsregler för forskare och doktorander.',
  },
  {
    organ: 'SfU',
    title: 'Stricter Requirements for Swedish Citizenship',
    dok_id: 'HD01SfU28',
    dokumentnamn: 'HD01SfU28',
    url: 'https://data.riksdagen.se/dokument/HD01SfU28',
    doktyp: 'bet',
    summary: 'Skärpta krav för svenskt medborgarskap.',
  },
  {
    organ: 'SfU',
    title: 'New Application Rules for Residence and Work Permits',
    dok_id: 'HD01SfU27',
    dokumentnamn: 'HD01SfU27',
    url: 'https://data.riksdagen.se/dokument/HD01SfU27',
    doktyp: 'bet',
    summary: 'Nya ansökningsregler för uppehålls- och arbetstillstånd.',
  },
  {
    organ: 'SfU',
    title: 'Stricter Character Requirements for Residence Permits',
    dok_id: 'HD01SfU36',
    dokumentnamn: 'HD01SfU36',
    url: 'https://data.riksdagen.se/dokument/HD01SfU36',
    doktyp: 'bet',
    summary: 'Skärpta vandelskrav för uppehållstillstånd.',
  },
  {
    organ: 'SfU',
    title: 'Stricter Deportation Rules for Criminal Offences',
    dok_id: 'HD01SfU33',
    dokumentnamn: 'HD01SfU33',
    url: 'https://data.riksdagen.se/dokument/HD01SfU33',
    doktyp: 'bet',
    summary: 'Skärpta utvisningsregler vid brott.',
  },
  {
    organ: 'SfU',
    title: 'A New Reception Act',
    dok_id: 'HD01SfU35',
    dokumentnamn: 'HD01SfU35',
    url: 'https://data.riksdagen.se/dokument/HD01SfU35',
    doktyp: 'bet',
    summary: 'En ny mottagningslag för asylsökande.',
  },
  {
    organ: 'SfU',
    title: 'Strengthened Return Operations and Immigration Control',
    dok_id: 'HD01SfU32',
    dokumentnamn: 'HD01SfU32',
    url: 'https://data.riksdagen.se/dokument/HD01SfU32',
    doktyp: 'bet',
    summary: 'Stärkt återvändandeverksamhet och utlänningskontroll.',
  },
  {
    organ: 'SfU',
    title: 'Distribution of Surplus in the Income Pension System',
    dok_id: 'HD01SfU25',
    dokumentnamn: 'HD01SfU25',
    url: 'https://data.riksdagen.se/dokument/HD01SfU25',
    doktyp: 'bet',
    summary: 'Fördelning av överskott i inkomstpensionssystemet.',
  },
  {
    organ: 'SfU',
    title: 'Benefit Lock and Sanction Fee in Social Insurance',
    dok_id: 'HD01SfU26',
    dokumentnamn: 'HD01SfU26',
    url: 'https://data.riksdagen.se/dokument/HD01SfU26',
    doktyp: 'bet',
    summary: 'Förmånsstopp och sanktionsavgift i socialförsäkringen.',
  },
  {
    organ: 'SfU',
    title: 'More Accurate and Correct Housing Allowance',
    dok_id: 'HD01SfU24',
    dokumentnamn: 'HD01SfU24',
    url: 'https://data.riksdagen.se/dokument/HD01SfU24',
    doktyp: 'bet',
    summary: 'Mer träffsäkert och korrekt bostadsbidrag.',
  },
  {
    organ: 'SfU',
    title: 'Social Insurance Changes Following Introduction of Controlled Housing and Security Detention',
    dok_id: 'HD01SfU29',
    dokumentnamn: 'HD01SfU29',
    url: 'https://data.riksdagen.se/dokument/HD01SfU29',
    doktyp: 'bet',
    summary: 'Socialförsäkringsändringar vid inrättande av kontrollerade boenden och säkerhetsarrest.',
  },
  // Education (UbU) – 1 report
  {
    organ: 'UbU',
    title: 'General School Issues',
    dok_id: 'HD01UbU7',
    dokumentnamn: 'HD01UbU7',
    url: 'https://data.riksdagen.se/dokument/HD01UbU7',
    doktyp: 'bet',
    summary: 'Allmänna skolfrågor och grundläggande utbildningspolitik.',
  },
  // Constitution (KU) – 1 report
  {
    organ: 'KU',
    title: 'Postponement of Certain Matters',
    dok_id: 'HD01KU43',
    dokumentnamn: 'HD01KU43',
    url: 'https://data.riksdagen.se/dokument/HD01KU43',
    doktyp: 'bet',
    summary: 'Bordläggning av vissa ärenden till nästa valperiod.',
  },
];

// ---------------------------------------------------------------------------
// Watch-point data per date (for the "What to Watch" section)
// ---------------------------------------------------------------------------
const WATCH_POINTS_2026_02_18: Record<Language, Array<{ title: string; description: string }>> = {
  en: [
    { title: 'Ukraine Vote', description: 'The supplementary appropriations vote (FiU46) on March 11 will test cross-party consensus on defense spending.' },
    { title: 'Tax Reform', description: 'Data protection proposals for Skatteverket may trigger privacy advocacy pushback.' },
    { title: 'Housing Reform', description: 'The housing cooperative registry (CU28) could reshape property market transparency.' },
  ],
  sv: [
    { title: 'Ukrainaomröstning', description: 'Omröstningen om tilläggsbudgeten (FiU46) den 11 mars prövar partiernas enighet kring försvarsutgifter.' },
    { title: 'Skattereform', description: 'Dataskyddsförslagen för Skatteverket kan möta kritik från integritetsförespråkare.' },
    { title: 'Bostadsreform', description: 'Bostadsrättsregistret (CU28) kan öka transparensen på bostadsmarknaden.' },
  ],
  da: [
    { title: 'Ukraina-afstemning', description: 'Afstemningen om tillægsbevillingsloven (FiU46) den 11. marts vil teste tværpartikonsensus om forsvarsudgifter.' },
    { title: 'Skattereform', description: 'Databeskyttelsesforslag for Skatteverket kan møde modstand fra privatlivsfortalere.' },
    { title: 'Boligreform', description: 'Andelsboligregistret (CU28) kan øge gennemsigtigheden på boligmarkedet.' },
  ],
  no: [
    { title: 'Ukraina-avstemning', description: 'Avstemningen om tilleggsbevilgningsloven (FiU46) 11. mars vil teste tverrpartikonsensus om forsvarsutgifter.' },
    { title: 'Skattereform', description: 'Personvernforslag for Skatteverket kan møte motstand fra personvernforkjempere.' },
    { title: 'Boligreform', description: 'Borettslaget-registeret (CU28) kan øke gjennomsiktigheten i boligmarkedet.' },
  ],
  fi: [
    { title: 'Ukraina-äänestys', description: 'Lisätalousarvioäänestys (FiU46) 11. maaliskuuta testaa puolueiden yksimielisyyttä puolustusmenoista.' },
    { title: 'Verouudistus', description: 'Skatteverketin tietosuojaesitykset voivat kohdata yksityisyysaktivistien vastarintaa.' },
    { title: 'Asuntouudistus', description: 'Asunto-osakeyhtiörekisteri (CU28) voi lisätä asuntomarkkinoiden läpinäkyvyyttä.' },
  ],
  de: [
    { title: 'Ukraine-Abstimmung', description: 'Die Abstimmung über den Nachtragshaushalt (FiU46) am 11. März wird den überparteilichen Konsens bei Verteidigungsausgaben testen.' },
    { title: 'Steuerreform', description: 'Datenschutzvorschläge für Skatteverket könnten auf Widerstand von Datenschützern stoßen.' },
    { title: 'Wohnungsreform', description: 'Das Wohnungsgenossenschaftsregister (CU28) könnte die Transparenz am Immobilienmarkt erhöhen.' },
  ],
  fr: [
    { title: "Vote sur l'Ukraine", description: "Le vote sur le budget supplémentaire (FiU46) le 11 mars testera le consensus transpartisan sur les dépenses de défense." },
    { title: 'Réforme fiscale', description: 'Les propositions de protection des données pour Skatteverket pourraient susciter des objections de la part des défenseurs de la vie privée.' },
    { title: 'Réforme du logement', description: 'Le registre des coopératives d\'habitation (CU28) pourrait accroître la transparence du marché immobilier.' },
  ],
  es: [
    { title: 'Votación sobre Ucrania', description: 'La votación del presupuesto suplementario (FiU46) el 11 de marzo pondrá a prueba el consenso transpartidario sobre el gasto en defensa.' },
    { title: 'Reforma fiscal', description: 'Las propuestas de protección de datos para Skatteverket podrían encontrar resistencia de los defensores de la privacidad.' },
    { title: 'Reforma de vivienda', description: 'El registro de cooperativas de vivienda (CU28) podría aumentar la transparencia del mercado inmobiliario.' },
  ],
  nl: [
    { title: 'Oekraïne-stemming', description: 'De stemming over de suppletoire begroting (FiU46) op 11 maart zal de breed-partijconsensus over defensie-uitgaven testen.' },
    { title: 'Belastinghervorming', description: 'Gegevensbeschermingsvoorstellen voor Skatteverket kunnen weerstand oproepen van privacyadvocaten.' },
    { title: 'Woninghervorming', description: 'Het woningcoöperatieregister (CU28) kan de transparantie op de woningmarkt vergroten.' },
  ],
  ar: [
    { title: 'التصويت على أوكرانيا', description: 'سيختبر التصويت على قانون الاعتمادات التكميلية (FiU46) في 11 مارس التوافق عبر الأحزاب على الإنفاق الدفاعي.' },
    { title: 'الإصلاح الضريبي', description: 'قد تواجه مقترحات حماية البيانات لـ Skatteverket معارضة من المدافعين عن الخصوصية.' },
    { title: 'إصلاح الإسكان', description: 'قد يعزز سجل التعاونيات السكنية (CU28) الشفافية في سوق العقارات.' },
  ],
  he: [
    { title: 'הצבעה על אוקראינה', description: 'ההצבעה על הצעת התקציב הנוספת (FiU46) ב-11 במרץ תבחן את הקונצנזוס הבין-מפלגתי על הוצאות הביטחון.' },
    { title: 'רפורמה במס', description: 'הצעות להגנת מידע עבור Skatteverket עלולות להתמודד עם התנגדות מצד מגיני הפרטיות.' },
    { title: 'רפורמת דיור', description: 'רישום אגודות הדיור (CU28) עשוי להגביר את השקיפות בשוק הנדל"ן.' },
  ],
  ja: [
    { title: 'ウクライナ支援採決', description: '3月11日の補正予算案（FiU46）採決が、防衛費に関する超党派の合意を試します。' },
    { title: '税制改革', description: 'Skatteverketのデータ保護提案はプライバシー擁護者の反対に直面するかもしれません。' },
    { title: '住宅改革', description: '住宅組合登録簿（CU28）は不動産市場の透明性を高める可能性があります。' },
  ],
  ko: [
    { title: '우크라이나 지원 표결', description: '3월 11일 추가경정예산안(FiU46) 표결은 국방비에 대한 초당파적 합의를 시험할 것입니다.' },
    { title: '세제 개혁', description: 'Skatteverket의 개인정보보호 제안은 프라이버시 옹호자들의 반발에 직면할 수 있습니다.' },
    { title: '주택 개혁', description: '주택 협동조합 등기부(CU28)는 부동산 시장의 투명성을 높일 수 있습니다.' },
  ],
  zh: [
    { title: '乌克兰支持投票', description: '3月11日追加拨款法案（FiU46）的投票将考验各党派在国防开支上的跨党共识。' },
    { title: '税制改革', description: 'Skatteverket的数据保护提案可能会遭遇隐私倡导者的反对。' },
    { title: '住房改革', description: '住房合作社登记册（CU28）可能会提高房地产市场的透明度。' },
  ],
};

const WATCH_POINTS_2026_02_24: Record<Language, Array<{ title: string; description: string }>> = {
  en: [
    { title: 'Coalition Discipline', description: 'Chamber debates on all 20 reports will test coalition discipline, particularly on migration votes where SD support is essential.' },
    { title: 'Nuclear Siting', description: 'Nuclear siting decisions (NU24) could trigger local opposition and environmental legal challenges.' },
    { title: 'Implementation', description: 'Implementation timelines for the citizenship requirements (SfU28) and deportation framework (SfU33) will determine real-world impact.' },
  ],
  sv: [
    { title: 'Koalitionsdisciplin', description: 'Kammardebatten om alla 20 betänkanden prövar koalitionens sammanhållning, särskilt i migrationsfrågor där SD:s stöd är avgörande.' },
    { title: 'Kärnkraftslokalisering', description: 'Beslut om lokalisering av kärnkraft (NU24) kan utlösa lokalt motstånd och juridiska överklaganden.' },
    { title: 'Implementering', description: 'Tidslinjerna för genomförande av medborgarskapskraven (SfU28) och utvisningsramverket (SfU33) avgör den praktiska effekten.' },
  ],
  da: [
    { title: 'Koalitionsdisciplin', description: 'Kammerdebatten om alle 20 betænkninger vil teste koalitionens sammenhæng, særligt ved migrationsafstemninger, hvor SD\'s støtte er afgørende.' },
    { title: 'Kernekraftplacering', description: 'Beslutninger om placering af kernekraft (NU24) kan udløse lokal modstand og juridiske udfordringer.' },
    { title: 'Implementering', description: 'Tidsplanerne for implementering af statsborgerskabskravene (SfU28) og udvisningsrammen (SfU33) vil afgøre den reelle virkning.' },
  ],
  no: [
    { title: 'Koalisjonsdisiplin', description: 'Stortingsdebatten om alle 20 innstillingene vil teste koalisjonens samhold, spesielt ved migrasjonsvotering der SD-støtte er avgjørende.' },
    { title: 'Kjernekraftlokalisering', description: 'Beslutninger om plassering av kjernekraftverk (NU24) kan utløse lokal motstand og juridiske utfordringer.' },
    { title: 'Implementering', description: 'Tidsplanene for gjennomføring av statsborgerskapskravene (SfU28) og utvisningsrammene (SfU33) vil avgjøre den praktiske effekten.' },
  ],
  fi: [
    { title: 'Koalition kurinalaisuus', description: 'Kaikista 20 mietinnöstä käytävät täysistuntodebatit testaavat koalition yhtenäisyyttä, erityisesti maahanmuuttoäänestyksissä, joissa SD:n tuki on ratkaisevaa.' },
    { title: 'Ydinvoiman sijainti', description: 'Ydinvoimaloiden sijaintipäätökset (NU24) voivat laukaista paikallista vastustusta ja oikeudellisia haasteita.' },
    { title: 'Toimeenpano', description: 'Kansalaisuusvaatimusten (SfU28) ja karkotuskehyksen (SfU33) toimeenpanoaikataulu määrittää käytännön vaikutuksen.' },
  ],
  de: [
    { title: 'Koalitionsdisziplin', description: 'Die Kammerdebatten über alle 20 Berichte werden die Koalitionsdisziplin testen, besonders bei Migrationsabstimmungen, bei denen SD-Unterstützung entscheidend ist.' },
    { title: 'Kernkraftstandorte', description: 'Entscheidungen über Kernkraftstandorte (NU24) könnten lokalen Widerstand und rechtliche Anfechtungen auslösen.' },
    { title: 'Umsetzung', description: 'Die Umsetzungszeitpläne für die Staatsbürgerschaftsanforderungen (SfU28) und den Abschiebungsrahmen (SfU33) werden die reale Wirkung bestimmen.' },
  ],
  fr: [
    { title: 'Discipline de coalition', description: 'Les débats en chambre sur les 20 rapports testeront la discipline de la coalition, notamment lors des votes sur la migration où le soutien du SD est essentiel.' },
    { title: 'Sites nucléaires', description: 'Les décisions de localisation nucléaire (NU24) pourraient susciter une opposition locale et des contestations juridiques environnementales.' },
    { title: 'Mise en œuvre', description: "Les calendriers de mise en œuvre des exigences de citoyenneté (SfU28) et du cadre d'expulsion (SfU33) détermineront l'impact réel." },
  ],
  es: [
    { title: 'Disciplina de coalición', description: 'Los debates en cámara sobre los 20 informes pondrán a prueba la disciplina de la coalición, especialmente en las votaciones de migración donde el apoyo del SD es esencial.' },
    { title: 'Emplazamientos nucleares', description: 'Las decisiones de emplazamiento nuclear (NU24) podrían generar oposición local y desafíos legales medioambientales.' },
    { title: 'Implementación', description: 'Los plazos de implementación de los requisitos de ciudadanía (SfU28) y el marco de deportación (SfU33) determinarán el impacto real.' },
  ],
  nl: [
    { title: 'Coalitiediscipline', description: 'De kamerdebates over alle 20 rapporten zullen de coalitiediscipline testen, met name bij migratiestemmen waarbij SD-steun essentieel is.' },
    { title: 'Nucleaire locaties', description: 'Beslissingen over kerncentrale-locaties (NU24) kunnen lokale weerstand en juridische uitdagingen op milieugebied uitlokken.' },
    { title: 'Implementatie', description: 'De implementatietijdlijnen voor de staatsburgereisenburger (SfU28) en het uitzettingskader (SfU33) bepalen de reële impact.' },
  ],
  ar: [
    { title: 'انضباط الائتلاف', description: 'ستختبر النقاشات البرلمانية حول جميع التقارير الـ20 انضباط الائتلاف، لا سيما في التصويتات المتعلقة بالهجرة حيث يكون دعم SD ضروريًا.' },
    { title: 'مواقع الطاقة النووية', description: 'قد تُثير قرارات تحديد مواقع الطاقة النووية (NU24) معارضة محلية وتحديات قانونية بيئية.' },
    { title: 'التنفيذ', description: 'ستحدد جداول تنفيذ متطلبات الجنسية (SfU28) وإطار الترحيل (SfU33) الأثر الفعلي.' },
  ],
  he: [
    { title: 'משמעת קואליציונית', description: 'הדיונים בכנסת על כל 20 הדוחות יבחנו את משמעת הקואליציה, במיוחד בהצבעות הגירה שבהן תמיכת SD חיונית.' },
    { title: 'אתרים גרעיניים', description: 'החלטות על מיקום מתקנים גרעיניים (NU24) עלולות לעורר התנגדות מקומית ואתגרים משפטיים סביבתיים.' },
    { title: 'יישום', description: 'לוחות הזמנים ליישום דרישות האזרחות (SfU28) ומסגרת הגירוש (SfU33) יקבעו את ההשפעה המעשית.' },
  ],
  ja: [
    { title: '連立の統制', description: '20の報告書すべてに関する議会討論は、SDの支援が不可欠な移住問題の投票で特に連立の統制を試すことになります。' },
    { title: '原子力施設の立地', description: '原子力施設の立地決定（NU24）は地域の反対や環境法的課題を引き起こす可能性があります。' },
    { title: '実施', description: '市民権要件（SfU28）と強制送還枠組み（SfU33）の実施スケジュールが実際の影響を決定します。' },
  ],
  ko: [
    { title: '연립 기강', description: '20개 보고서 전체에 대한 의회 토론은 SD 지지가 필수적인 이민 투표를 중심으로 연립의 기강을 시험할 것입니다.' },
    { title: '원자력 발전소 부지', description: '원자력 발전소 부지 결정(NU24)은 지역 반발과 환경 법적 도전을 촉발할 수 있습니다.' },
    { title: '시행', description: '시민권 요건(SfU28)과 추방 프레임워크(SfU33)의 시행 일정이 실제 영향을 결정할 것입니다.' },
  ],
  zh: [
    { title: '联合政府纪律', description: '所有20份报告的议会辩论将考验联合政府纪律，特别是在SD支持至关重要的移民投票中。' },
    { title: '核电站选址', description: '核电站选址决定（NU24）可能引发地方反对和环境法律挑战。' },
    { title: '实施', description: '公民资格要求（SfU28）和驱逐框架（SfU33）的实施时间表将决定实际影响。' },
  ],
};

// ---------------------------------------------------------------------------
// Helper: extract lede paragraph from existing HTML
// ---------------------------------------------------------------------------
function extractLede(html: string): string {
  const m = html.match(/<p class="lede">([\s\S]*?)<\/p>/);
  return m ? m[0] : '';
}

// ---------------------------------------------------------------------------
// Helper: replace article-content body (keep lede, replace the rest)
// ---------------------------------------------------------------------------
function replaceBody(html: string, newBodyHtml: string): string {
  // Find the article-content div
  const contentStart = html.indexOf('<div class="article-content">');
  if (contentStart === -1) return html;

  // Find the end of the lede paragraph
  const ledeStart = html.indexOf('<p class="lede">', contentStart);
  if (ledeStart === -1) return html;
  const ledeEnd = html.indexOf('</p>', ledeStart) + 4; // include </p>

  // Find closing </div> of article-content (before </article>)
  const articleEnd = html.indexOf('</article>', contentStart);
  if (articleEnd === -1) return html;
  // The closing </div> is just before </article>, skip whitespace
  let divEnd = html.lastIndexOf('</div>', articleEnd);
  if (divEnd === -1) return html;
  divEnd += 6; // include </div>

  return (
    html.slice(0, ledeEnd) +
    '\n\n' +
    newBodyHtml +
    '\n\n  ' +
    html.slice(divEnd)
  );
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main(): Promise<void> {
  const dateGroups: Array<{ dates: string[]; reports: RawDocument[]; watchPoints: Record<Language, Array<{ title: string; description: string }>> }> = [
    {
      dates: ['2026-02-16', '2026-02-17', '2026-02-18'],
      reports: REPORTS_2026_02_18,
      watchPoints: WATCH_POINTS_2026_02_18,
    },
    {
      dates: ['2026-02-24'],
      reports: REPORTS_2026_02_24,
      watchPoints: WATCH_POINTS_2026_02_24,
    },
  ];

  let fixed = 0;
  let skipped = 0;
  let errors = 0;

  for (const group of dateGroups) {
    // Pre-generate body HTML for each language
    const bodyByLang: Partial<Record<Language, string>> = {};
    for (const lang of NON_ENGLISH_LANGS) {
      const body = generateArticleContent({ reports: group.reports } as ArticleContentData, 'committee-reports', lang);
      const watchPoints = group.watchPoints[lang] || group.watchPoints.en;
      const watchSection = generateWatchSection(watchPoints, lang);
      bodyByLang[lang] = body + '\n' + watchSection;
    }

    for (const date of group.dates) {
      for (const lang of NON_ENGLISH_LANGS) {
        const filePath = path.join(NEWS_DIR, `${date}-committee-reports-${lang}.html`);

        if (!fs.existsSync(filePath)) {
          console.log(`  ⏭  Skipping (not found): ${path.basename(filePath)}`);
          skipped++;
          continue;
        }

        const original = fs.readFileSync(filePath, 'utf8');
        const newBody = bodyByLang[lang];
        if (!newBody) {
          console.error(`  ✗ No body generated for ${lang}`);
          errors++;
          continue;
        }

        const fixed_html = replaceBody(original, newBody);
        if (fixed_html === original) {
          console.log(`  ⚠️  No change: ${path.basename(filePath)}`);
          skipped++;
          continue;
        }

        fs.writeFileSync(filePath, fixed_html, 'utf8');
        console.log(`  ✅ Fixed: ${path.basename(filePath)}`);
        fixed++;
      }
    }
  }

  console.log(`\n📊 Summary: ${fixed} fixed, ${skipped} skipped, ${errors} errors`);
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
