/**
 * @module data-transformers/constants
 * @description Localisation constants and lookup tables for the data
 * transformation pipeline. Contains CONTENT_LABELS (14-language i18n
 * map), COMMITTEE_NAMES, and LOCALE_MAP.
 *
 * @author Hack23 AB
 * @license Apache-2.0
 */

import type { Language } from '../types/language.js';
import type { ContentLabelSet, CommitteeNameMap } from '../types/content.js';

/**
 * Map of custom locale codes to Intl-compatible locale strings.
 * Used for date/time formatting across all 14 supported languages.
 */
export const LOCALE_MAP: Record<string, string> = {
  en: 'en-GB', sv: 'sv-SE', da: 'da-DK', no: 'no-NO', fi: 'fi-FI',
  de: 'de-DE', fr: 'fr-FR', es: 'es-ES', nl: 'nl-NL', ar: 'ar-SA',
  he: 'he-IL', ja: 'ja-JP', ko: 'ko-KR', zh: 'zh-CN'
};

/**
 * Map Swedish committee codes to full names for richer descriptions.
 * Uses "Committee on [Subject]" English naming convention.
 */
export const COMMITTEE_NAMES: CommitteeNameMap = {
  AU: { en: 'Committee on Labour Market Affairs', sv: 'Arbetsmarknadsutskottet' },
  CU: { en: 'Committee on Civil Affairs', sv: 'Civilutskottet' },
  FiU: { en: 'Committee on Finance', sv: 'Finansutskottet' },
  FöU: { en: 'Committee on Defence', sv: 'Försvarsutskottet' },
  JuU: { en: 'Committee on Justice', sv: 'Justitieutskottet' },
  KU: { en: 'Committee on the Constitution', sv: 'Konstitutionsutskottet' },
  KrU: { en: 'Committee on Cultural Affairs', sv: 'Kulturutskottet' },
  MJU: { en: 'Committee on Environment and Agriculture', sv: 'Miljö- och jordbruksutskottet' },
  NU: { en: 'Committee on Industry and Trade', sv: 'Näringsutskottet' },
  SkU: { en: 'Committee on Taxation', sv: 'Skatteutskottet' },
  SfU: { en: 'Committee on Social Insurance', sv: 'Socialförsäkringsutskottet' },
  SoU: { en: 'Committee on Social Affairs', sv: 'Socialutskottet' },
  TU: { en: 'Committee on Transport', sv: 'Trafikutskottet' },
  UbU: { en: 'Committee on Education', sv: 'Utbildningsutskottet' },
  UU: { en: 'Committee on Foreign Affairs', sv: 'Utrikesutskottet' },
};

// Multi-language labels for content generation
export const CONTENT_LABELS: Record<Language, ContentLabelSet> = {
  en: {
    whyMatters: 'Why This Week Matters',
    whyMattersDefault: 'This week features significant parliamentary activity with key debates, committee meetings, and government consultations that will shape Sweden\'s political landscape.',
    keyEvents: 'Key Events This Week',
    whatToWatch: 'What to Watch',
    latestReports: 'Latest Committee Reports',
    noReports: 'No committee reports available at this time.',
    committee: 'Committee', document: 'Document',
    reportDefault: 'Committee report on parliamentary matter.',
    govProps: 'Government Propositions',
    noProps: 'No government propositions available at this time.',
    propDefault: 'Government proposal to Parliament.',
    oppMotions: 'Opposition Motions',
    noMotions: 'No opposition motions available at this time.',
    author: 'Author', party: 'Party',
    motionDefault: 'Parliamentary motion by opposition member.',
    genericContent: 'Content generation in progress.',
    monitorDev: 'Monitor developments and outcomes',
    committeeDebates: 'Committee Debates',
    committeeDebatesDesc: (n: number): string => `${n} committee reports scheduled for chamber debate`,
    govProposals: 'Government Proposals',
    govProposalsDesc: (n: number): string => `${n} new government propositions under review`,
    weekAhead: 'Week Ahead', committeeReportsTag: 'Committee Reports',
    govPropsTag: 'Government Propositions', oppMotionsTag: 'Opposition Motions',
    // Enhanced summary labels
    committeeReport: 'committee report',
    on: 'on',
    governmentProposition: 'Government proposition',
    regarding: 'regarding',
    referredTo: 'referred to',
    motionBy: 'Motion by',
    parliamentaryMotion: 'Parliamentary motion',
    unknown: 'Unknown',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `The Swedish Parliament's committees have published ${n} new reports, reflecting ongoing legislative work across multiple policy areas.`,
    reportSignificance: 'This report addresses',
    readFullReport: 'Read the full report',
    propsOverview: (n: number): string => `The government has submitted ${n} new propositions to Parliament, each requiring committee review and chamber debate before potential adoption.`,
    propSignificance: 'This proposition concerns',
    readFullProp: 'Read the full proposition',
    motionsOverview: (n: number): string => `Opposition MPs have filed ${n} new motions, pressing the government on issues ranging across policy domains.`,
    motionSignificance: 'This motion addresses',
    readFullMotion: 'Read the full motion',
    policyContext: 'Policy context',
    filedBy: 'Filed by',
    politicalContext: 'Political Context',
    policyImplications: 'Policy Implications',
    keyTakeaways: 'Key Takeaways',
    thematicAnalysis: 'Thematic Analysis',
    legislativePipeline: 'Legislative Pipeline',
    oppositionStrategy: 'Opposition Strategy',
    coalitionDynamics: 'Coalition Dynamics',
    whatThisMeans: 'What This Means',
    whyItMatters: 'Why It Matters',
    committeeBreakdown: (n: number, c: number): string => `This batch of ${n} committee reports spans ${c} different committees, reflecting the breadth of legislative activity in the current parliamentary session. The thematic spread reveals the Riksdag's multi-front policy engagement and the government's legislative priorities.`,
    propsBreakdown: (n: number): string => `The government has submitted ${n} new propositions, signalling its policy priorities and the pace of its legislative agenda. Each proposition must navigate committee review and chamber debate, providing insight into the coalition's strategic direction and its ability to build cross-party support.`,
    motionsBreakdown: (n: number): string => `Opposition MPs have filed ${n} new motions, mapping the political fault lines in the current Riksdag. These motions reveal not just policy disagreements but the strategic positioning of parties as they prepare for the next electoral contest.`
,
    committeeCountContext: (n: number): string => `${n} reports from this committee signal intensive legislative work within its portfolio.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `Parliamentary committees have been active across ${committees} and ${extra} further policy domains.` : `Parliamentary committees have been active across ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `A total of ${n} reports demonstrates sustained legislative momentum and ongoing policy prioritisation.`,
    oppositionStrategyContext: (n: number): string => `Motions from ${n} different parties reveal the breadth of opposition political criticism and alternative policy agendas.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `These ${propCount} propositions touch on ${domainCount} policy domain${domainCount > 1 ? 's' : ''}, demonstrating the government's broad legislative ambition. Committee review and chamber debate will determine whether these proposals command sufficient support to become law.`,
    genericOverview: (n: number): string => `During this period, ${n} documents were processed in parliament, offering a snapshot of ongoing legislative work.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} motion${n > 1 ? 's' : ''} filed`,
    otherCommittee: 'Other committees',
    otherDocuments: 'Other documents',
    policySignificanceTouches: (domains: string): string => `Touches on ${domains}.`,
    policySignificanceGeneric: 'Requires committee review and chamber debate before a decision is reached.',
    processedThisPeriod: 'processed this period',
    generalMatters: 'General matters',
    responsesToProp: 'Responses to Government Propositions',
    independentMotions: 'Independent Motions',
    govEngagement: 'Government Department Engagement',
    twitterLabel1: 'Reading time',
    twitterLabel2: 'Article type',
    jobTitle: 'Political Intelligence Analyst',
    siteDescription: 'Swedish Parliament Intelligence Platform - Monitor political activity with systematic transparency'
  },
  sv: {
    whyMatters: 'Varför denna vecka är viktig',
    whyMattersDefault: 'Denna vecka innehåller betydande parlamentarisk aktivitet med viktiga debatter, kommittémöten och regeringskonsultationer som kommer att forma Sveriges politiska landskap.',
    keyEvents: 'Nyckelhändelser denna vecka',
    whatToWatch: 'Vad man ska följa',
    latestReports: 'Senaste kommittérapporter',
    noReports: 'Inga kommittérapporter tillgängliga för tillfället.',
    committee: 'Kommitté', document: 'Dokument',
    reportDefault: 'Kommittérapport om riksdagsärende.',
    govProps: 'Regeringens propositioner',
    noProps: 'Inga regeringspropositioner tillgängliga för tillfället.',
    propDefault: 'Regeringens förslag till riksdagen.',
    oppMotions: 'Oppositionens motioner',
    noMotions: 'Inga oppositionsmotioner tillgängliga för tillfället.',
    author: 'Författare', party: 'Parti',
    motionDefault: 'Riksdagsmotion av oppositionsmedlem.',
    genericContent: 'Innehållsgenerering pågår.',
    monitorDev: 'Övervaka utveckling och resultat',
    committeeDebates: 'Kommittédebatter',
    committeeDebatesDesc: (n: number): string => `${n} kommittérapporter planerade för kammarens debatt`,
    govProposals: 'Regeringsförslag',
    govProposalsDesc: (n: number): string => `${n} nya regeringspropositioner under granskning`,
    weekAhead: 'Veckan som kommer', committeeReportsTag: 'Kommittérapporter',
    govPropsTag: 'Regeringens propositioner', oppMotionsTag: 'Oppositionens motioner',
    // Enhanced summary labels
    committeeReport: 'kommittérapport',
    on: 'om',
    governmentProposition: 'Regeringens proposition',
    regarding: 'angående',
    referredTo: 'hänvisad till',
    motionBy: 'Motion av',
    parliamentaryMotion: 'Riksdagsmotion',
    unknown: 'Okänd',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `Riksdagens utskott har publicerat ${n} nya betänkanden som speglar det pågående lagstiftningsarbetet inom flera politikområden.`,
    reportSignificance: 'Detta betänkande behandlar',
    readFullReport: 'Läs hela betänkandet',
    propsOverview: (n: number): string => `Regeringen har överlämnat ${n} nya propositioner till riksdagen, var och en kräver utskottsbehandling och kammardebatt.`,
    propSignificance: 'Denna proposition avser',
    readFullProp: 'Läs hela propositionen',
    motionsOverview: (n: number): string => `Oppositionsriksdagsledamöter har lämnat in ${n} nya motioner som pressar regeringen inom flera politikområden.`,
    motionSignificance: 'Denna motion behandlar',
    readFullMotion: 'Läs hela motionen',
    policyContext: 'Politisk kontext',
    filedBy: 'Inlämnad av',
    politicalContext: 'Politisk kontext',
    policyImplications: 'Politiska konsekvenser',
    keyTakeaways: 'Centrala slutsatser',
    thematicAnalysis: 'Tematisk analys',
    legislativePipeline: 'Lagstiftningsprocess',
    oppositionStrategy: 'Oppositionens strategi',
    coalitionDynamics: 'Koalitionsdynamik',
    whatThisMeans: 'Vad detta innebär',
    whyItMatters: 'Varför det spelar roll',
    committeeBreakdown: (n: number, c: number): string => `Denna omgång med ${n} utskottsbetänkanden omfattar ${c} olika utskott, vilket speglar bredden i riksdagens lagstiftningsarbete under innevarande session.`,
    propsBreakdown: (n: number): string => `Regeringen har överlämnat ${n} nya propositioner, som signalerar dess politiska prioriteringar och takten i den lagstiftande agendan.`,
    motionsBreakdown: (n: number): string => `Oppositionsledamöter har lämnat in ${n} nya motioner som kartlägger de politiska skiljelinjerna i nuvarande riksdag.`
,
    committeeCountContext: (n: number): string => `${n} betänkanden från detta utskott signalerar intensivt lagstiftningsarbete inom dess ansvarsområde.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `Riksdagens utskott har varit aktiva inom ${committees} och ${extra} ytterligare områden.` : `Riksdagens utskott har varit aktiva inom ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `Totalt ${n} betänkanden visar lagstiftande momentum och pågående politisk prioritering.`,
    oppositionStrategyContext: (n: number): string => `Motioner från ${n} olika partier visar bredden i oppositionens politiska kritik och alternativa agenda.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `Dessa ${propCount} propositioner berör ${domainCount} politikområde${domainCount > 1 ? 'n' : ''}, vilket visar regeringens breda lagstiftningsambition. Utskottsbehandling och kammardebatt avgör om förslagen vinner tillräckligt stöd för att bli lag.`,
    genericOverview: (n: number): string => `Under perioden har ${n} dokument behandlats i riksdagen, vilket ger en bild av det pågående lagstiftningsarbetet.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} motion${n > 1 ? 'er' : ''} inlämnade`,
    otherCommittee: 'Övriga utskott',
    otherDocuments: 'Övriga dokument',
    policySignificanceTouches: (domains: string): string => `Berör ${domains}.`,
    policySignificanceGeneric: 'Kräver utskottsbehandling och kammardebatt innan beslut fattas.',
    processedThisPeriod: 'behandlade denna period',
    generalMatters: 'Övriga frågor',
    responsesToProp: 'Svar på propositioner',
    independentMotions: 'Övriga motioner',
    govEngagement: 'Regeringsdepartementens engagemang',
    twitterLabel1: 'Lästid',
    twitterLabel2: 'Artikeltyp',
    jobTitle: 'Politisk underrättelseanalytiker',
    siteDescription: 'Riksdagsmonitor – övervaka politisk aktivitet med systematisk transparens'
  },
  da: {
    whyMatters: 'Hvorfor denne uge er vigtig',
    whyMattersDefault: 'Denne uge byder på vigtig parlamentarisk aktivitet med centrale debatter, udvalgsmøder og regeringskonsultationer.',
    keyEvents: 'Vigtige begivenheder denne uge',
    whatToWatch: 'Hvad man skal følge',
    latestReports: 'Seneste udvalgsbetænkninger',
    noReports: 'Ingen udvalgsbetænkninger tilgængelige på nuværende tidspunkt.',
    committee: 'Udvalg', document: 'Dokument',
    reportDefault: 'Udvalgsbetænkning om parlamentarisk sag.',
    govProps: 'Regeringsforslag',
    noProps: 'Ingen regeringsforslag tilgængelige på nuværende tidspunkt.',
    propDefault: 'Regeringsforslag til parlamentet.',
    oppMotions: 'Oppositionsforslag',
    noMotions: 'Ingen oppositionsforslag tilgængelige på nuværende tidspunkt.',
    author: 'Forfatter', party: 'Parti',
    motionDefault: 'Parlamentarisk forslag fra oppositionsmedlem.',
    genericContent: 'Indhold genereres.',
    monitorDev: 'Overvåg udviklingen og resultaterne',
    committeeDebates: 'Udvalgsedebatter',
    committeeDebatesDesc: (n: number): string => `${n} udvalgsbetænkninger planlagt til kammerdebat`,
    govProposals: 'Regeringsforslag',
    govProposalsDesc: (n: number): string => `${n} nye regeringsforslag under behandling`,
    weekAhead: 'Ugen fremover', committeeReportsTag: 'Udvalgsbetænkninger',
    govPropsTag: 'Regeringsforslag', oppMotionsTag: 'Oppositionsforslag',
    // Enhanced summary labels
    committeeReport: 'udvalgsbetænkning',
    on: 'om',
    governmentProposition: 'Regeringsforslag',
    regarding: 'vedrørende',
    referredTo: 'henvist til',
    motionBy: 'Forslag fra',
    parliamentaryMotion: 'Parlamentarisk forslag',
    unknown: 'Ukendt',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `Sverigesrigsdagens udvalg har offentliggjort ${n} nye betænkninger, der afspejler igangværende lovgivningsarbejde.`,
    reportSignificance: 'Denne betænkning omhandler',
    readFullReport: 'Læs hele betænkningen',
    propsOverview: (n: number): string => `Regeringen har fremsat ${n} nye lovforslag til parlamentet.`,
    propSignificance: 'Dette forslag vedrører',
    readFullProp: 'Læs hele forslaget',
    motionsOverview: (n: number): string => `Oppositionsmedlemmer har indgivet ${n} nye forslag.`,
    motionSignificance: 'Dette forslag omhandler',
    readFullMotion: 'Læs hele forslaget',
    policyContext: 'Politisk kontekst',
    filedBy: 'Indgivet af',
    politicalContext: 'Politisk kontekst',
    policyImplications: 'Politiske konsekvenser',
    keyTakeaways: 'Centrale konklusioner',
    thematicAnalysis: 'Tematisk analyse',
    legislativePipeline: 'Lovgivningsprocessen',
    oppositionStrategy: 'Oppositionens strategi',
    coalitionDynamics: 'Koalitionsdynamik',
    whatThisMeans: 'Hvad dette betyder',
    whyItMatters: 'Hvorfor det er vigtigt',
    committeeBreakdown: (n: number, c: number): string => `Denne omgang med ${n} udvalgsbetænkninger dækker ${c} forskellige udvalg.`,
    propsBreakdown: (n: number): string => `Regeringen har fremsat ${n} nye lovforslag.`,
    motionsBreakdown: (n: number): string => `Oppositionsmedlemmer har indgivet ${n} nye forslag.`
,
    committeeCountContext: (n: number): string => `${n} betænkninger fra dette udvalg signalerer intensivt lovgivningsarbejde.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `Parlamentets udvalg har været aktive inden for ${committees} og ${extra} yderligere politikområder.` : `Parlamentets udvalg har været aktive inden for ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `I alt ${n} betænkninger viser vedvarende lovgivningsmæssig fremdrift.`,
    oppositionStrategyContext: (n: number): string => `Forslag fra ${n} forskellige partier viser bredden i oppositionens politiske kritik.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `Disse ${propCount} lovforslag berører ${domainCount} politikområde${domainCount > 1 ? 'r' : ''}, hvilket viser regeringens brede lovgivningsambition.`,
    genericOverview: (n: number): string => `I denne periode er ${n} dokumenter blevet behandlet i parlamentet.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} forslag indgivet`,
    otherCommittee: 'Andre udvalg',
    otherDocuments: 'Andre dokumenter',
    policySignificanceTouches: (domains: string): string => `Berører ${domains}.`,
    policySignificanceGeneric: 'Kræver udvalgsbehandling og kammerdebat, før der træffes afgørelse.',
    processedThisPeriod: 'behandlet i denne periode',
    generalMatters: 'Generelle spørgsmål',
    responsesToProp: 'Svar på regeringsforslag',
    independentMotions: 'Andre forslag',
    govEngagement: 'Regeringsdepartementernes engagement',
    twitterLabel1: 'Læsetid',
    twitterLabel2: 'Artikeltype',
    jobTitle: 'Politisk efterretningsanalytiker',
    siteDescription: 'Svensk parlamentsovervågning – følg politisk aktivitet med systematisk gennemsigtighed'
  },
  no: {
    whyMatters: 'Hvorfor denne uken er viktig',
    whyMattersDefault: 'Denne uken byr på viktig parlamentarisk aktivitet med sentrale debatter, komitémøter og regjeringskonsultasjoner.',
    keyEvents: 'Viktige hendelser denne uken',
    whatToWatch: 'Hva man bør følge med på',
    latestReports: 'Siste komitéinnstillinger',
    noReports: 'Ingen komitéinnstillinger tilgjengelige for øyeblikket.',
    committee: 'Komité', document: 'Dokument',
    reportDefault: 'Komitéinnstilling om parlamentarisk sak.',
    govProps: 'Regjeringens proposisjoner',
    noProps: 'Ingen regjeringsproposisjoner tilgjengelige for øyeblikket.',
    propDefault: 'Regjeringens forslag til parlamentet.',
    oppMotions: 'Opposisjonsforslag',
    noMotions: 'Ingen opposisjonsforslag tilgjengelige for øyeblikket.',
    author: 'Forfatter', party: 'Parti',
    motionDefault: 'Parlamentarisk forslag fra opposisjonsmedlem.',
    genericContent: 'Innholdsgenerering pågår.',
    monitorDev: 'Overvåk utviklingen og resultatene',
    committeeDebates: 'Komitédebatter',
    committeeDebatesDesc: (n: number): string => `${n} komitéinnstillinger planlagt for kammerdebatt`,
    govProposals: 'Regjeringsforslag',
    govProposalsDesc: (n: number): string => `${n} nye regjeringsproposisjoner under vurdering`,
    weekAhead: 'Uke fremover', committeeReportsTag: 'Komitéinnstillinger',
    govPropsTag: 'Regjeringens proposisjoner', oppMotionsTag: 'Opposisjonsforslag',
    // Enhanced summary labels
    committeeReport: 'komitéinnstilling',
    on: 'om',
    governmentProposition: 'Regjeringens proposisjon',
    regarding: 'vedrørende',
    referredTo: 'henvist til',
    motionBy: 'Forslag fra',
    parliamentaryMotion: 'Parlamentarisk forslag',
    unknown: 'Ukjent',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `Den svenske riksdagens komiteer har publisert ${n} nye innstillinger som gjenspeiler pågående lovgivningsarbeid.`,
    reportSignificance: 'Denne innstillingen omhandler',
    readFullReport: 'Les hele innstillingen',
    propsOverview: (n: number): string => `Regjeringen har fremmet ${n} nye proposisjoner til Stortinget.`,
    propSignificance: 'Denne proposisjonen gjelder',
    readFullProp: 'Les hele proposisjonen',
    motionsOverview: (n: number): string => `Opposisjonsmedlemmer har fremmet ${n} nye forslag.`,
    motionSignificance: 'Dette forslaget omhandler',
    readFullMotion: 'Les hele forslaget',
    policyContext: 'Politisk kontekst',
    filedBy: 'Innsendt av',
    politicalContext: 'Politisk kontekst',
    policyImplications: 'Politiske konsekvenser',
    keyTakeaways: 'Sentrale konklusjoner',
    thematicAnalysis: 'Tematisk analyse',
    legislativePipeline: 'Lovgivningsprosessen',
    oppositionStrategy: 'Opposisjonens strategi',
    coalitionDynamics: 'Koalisjonsdynamikk',
    whatThisMeans: 'Hva dette betyr',
    whyItMatters: 'Hvorfor det er viktig',
    committeeBreakdown: (n: number, c: number): string => `Denne runden med ${n} komitéinnstillinger dekker ${c} forskjellige komiteer.`,
    propsBreakdown: (n: number): string => `Regjeringen har fremmet ${n} nye proposisjoner.`,
    motionsBreakdown: (n: number): string => `Opposisjonsmedlemmer har innsendt ${n} nye forslag.`
,
    committeeCountContext: (n: number): string => `${n} innstillinger fra denne komiteen signaliserer intensivt lovgivningsarbeid.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `Stortingets komiteer har vært aktive innen ${committees} og ${extra} ytterligere politikkområder.` : `Stortingets komiteer har vært aktive innen ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `Totalt ${n} innstillinger viser vedvarende lovgivende fremdrift.`,
    oppositionStrategyContext: (n: number): string => `Forslag fra ${n} ulike partier viser bredden i opposisjonens politiske kritikk.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `Disse ${propCount} proposisjonene berører ${domainCount} politikkområde${domainCount > 1 ? 'r' : ''}, og viser regjeringens brede lovgivningsambisjon.`,
    genericOverview: (n: number): string => `I denne perioden er ${n} dokumenter blitt behandlet i parlamentet.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} forslag innsendt`,
    otherCommittee: 'Andre komiteer',
    otherDocuments: 'Andre dokumenter',
    policySignificanceTouches: (domains: string): string => `Berører ${domains}.`,
    policySignificanceGeneric: 'Krever komitébehandling og kammerdebatt før avgjørelse fattes.',
    processedThisPeriod: 'behandlet denne perioden',
    generalMatters: 'Generelle spørsmål',
    responsesToProp: 'Svar på regjeringforslag',
    independentMotions: 'Andre forslag',
    govEngagement: 'Regjeringsdepartementenes engasjement',
    twitterLabel1: 'Lesetid',
    twitterLabel2: 'Artikkeltype',
    jobTitle: 'Politisk etterretningsanalytiker',
    siteDescription: 'Svensk parlamentsovervåkning – følg politisk aktivitet med systematisk åpenhet'
  },
  fi: {
    whyMatters: 'Miksi tämä viikko on tärkeä',
    whyMattersDefault: 'Tällä viikolla on merkittävää parlamentaarista toimintaa, johon kuuluu tärkeitä keskusteluja, valiokuntakokouksia ja hallituksen kuulemisia.',
    keyEvents: 'Viikon tärkeimmät tapahtumat',
    whatToWatch: 'Mitä seurata',
    latestReports: 'Uusimmat valiokuntamietinnöt',
    noReports: 'Ei valiokuntamietintöjä saatavilla tällä hetkellä.',
    committee: 'Valiokunta', document: 'Asiakirja',
    reportDefault: 'Valiokuntamietintö parlamentaarisesta asiasta.',
    govProps: 'Hallituksen esitykset',
    noProps: 'Ei hallituksen esityksiä saatavilla tällä hetkellä.',
    propDefault: 'Hallituksen esitys eduskunnalle.',
    oppMotions: 'Opposition aloitteet',
    noMotions: 'Ei opposition aloitteita saatavilla tällä hetkellä.',
    author: 'Tekijä', party: 'Puolue',
    motionDefault: 'Opposition jäsenen eduskunta-aloite.',
    genericContent: 'Sisältöä luodaan.',
    monitorDev: 'Seuraa kehitystä ja tuloksia',
    committeeDebates: 'Valiokuntakeskustelut',
    committeeDebatesDesc: (n: number): string => `${n} valiokuntamietintöä aikataulutettu täysistuntokeskusteluun`,
    govProposals: 'Hallituksen esitykset',
    govProposalsDesc: (n: number): string => `${n} uutta hallituksen esitystä käsittelyssä`,
    weekAhead: 'Tuleva viikko', committeeReportsTag: 'Valiokuntamietinnöt',
    govPropsTag: 'Hallituksen esitykset', oppMotionsTag: 'Opposition aloitteet',
    // Enhanced summary labels
    committeeReport: 'valiokunnan mietintö',
    on: 'aiheesta',
    governmentProposition: 'Hallituksen esitys',
    regarding: 'koskien',
    referredTo: 'lähetetty valiokuntaan',
    motionBy: 'Aloite',
    parliamentaryMotion: 'Eduskunnan aloite',
    unknown: 'Tuntematon',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `Ruotsin valtiopäivien valiokunnat ovat julkaisseet ${n} uutta mietintöä, jotka heijastavat meneillään olevaa lainsäädäntötyötä.`,
    reportSignificance: 'Tämä mietintö käsittelee',
    readFullReport: 'Lue koko mietintö',
    propsOverview: (n: number): string => `Hallitus on jättänyt ${n} uutta esitystä eduskunnalle.`,
    propSignificance: 'Tämä esitys koskee',
    readFullProp: 'Lue koko esitys',
    motionsOverview: (n: number): string => `Opposition kansanedustajat ovat jättäneet ${n} uutta aloitetta.`,
    motionSignificance: 'Tämä aloite käsittelee',
    readFullMotion: 'Lue koko aloite',
    policyContext: 'Poliittinen konteksti',
    filedBy: 'Jättänyt',
    politicalContext: 'Poliittinen konteksti',
    policyImplications: 'Poliittiset vaikutukset',
    keyTakeaways: 'Keskeiset havainnot',
    thematicAnalysis: 'Temaattinen analyysi',
    legislativePipeline: 'Lainsäädäntöprosessi',
    oppositionStrategy: 'Opposition strategia',
    coalitionDynamics: 'Koalitiodynamiikka',
    whatThisMeans: 'Mitä tämä tarkoittaa',
    whyItMatters: 'Miksi tämä on tärkeää',
    committeeBreakdown: (n: number, c: number): string => `Tämä erä ${n} valiokunnan mietintöä kattaa ${c} eri valiokuntaa.`,
    propsBreakdown: (n: number): string => `Hallitus on jättänyt ${n} uutta esitystä.`,
    motionsBreakdown: (n: number): string => `Oppositiokansanedustajat ovat jättäneet ${n} uutta aloitetta.`
,
    committeeCountContext: (n: number): string => `${n} mietintöä tästä valiokunnasta osoittavat intensiivistä lainsäädäntötyötä.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `Eduskunnan valiokunnat ovat olleet aktiivisia aloilla ${committees} ja ${extra} muulla politiikka-alueella.` : `Eduskunnan valiokunnat ovat olleet aktiivisia aloilla ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `Yhteensä ${n} mietintöä osoittaa jatkuvaa lainsäädännöllistä vauhtia.`,
    oppositionStrategyContext: (n: number): string => `${n} eri puolueen aloitteet osoittavat opposition poliittisen kritiikin laajuuden.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `Nämä ${propCount} esitystä koskevat ${domainCount} politiikka-aluetta, mikä osoittaa hallituksen laajaa lainsäädäntökunnianhimoa.`,
    genericOverview: (n: number): string => `Tänä aikana eduskunnassa käsiteltiin ${n} asiakirjaa.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} aloitetta jätetty`,
    otherCommittee: 'Muut valiokunnat',
    otherDocuments: 'Muut asiakirjat',
    policySignificanceTouches: (domains: string): string => `Koskee aloja ${domains}.`,
    policySignificanceGeneric: 'Vaatii valiokuntakäsittelyn ja täysistuntokeskustelun ennen päätöksentekoa.',
    processedThisPeriod: 'käsitelty tällä kaudella',
    generalMatters: 'Yleiset asiat',
    responsesToProp: 'Vastaukset hallituksen esityksiin',
    independentMotions: 'Muut aloitteet',
    govEngagement: 'Ministeriöiden osallistuminen',
    twitterLabel1: 'Lukuaika',
    twitterLabel2: 'Artikkelityyppi',
    jobTitle: 'Poliittinen tiedusteluanalyytikko',
    siteDescription: 'Ruotsin parlamentin seuranta – poliittisen toiminnan systemaattinen läpinäkyvyys'
  },
  de: {
    whyMatters: 'Warum diese Woche wichtig ist',
    whyMattersDefault: 'Diese Woche bietet bedeutende parlamentarische Aktivitäten mit wichtigen Debatten, Ausschusssitzungen und Regierungskonsultationen.',
    keyEvents: 'Wichtige Ereignisse diese Woche',
    whatToWatch: 'Was zu beobachten ist',
    latestReports: 'Neueste Ausschussberichte',
    noReports: 'Derzeit keine Ausschussberichte verfügbar.',
    committee: 'Ausschuss', document: 'Dokument',
    reportDefault: 'Ausschussbericht über parlamentarische Angelegenheit.',
    govProps: 'Regierungsvorlagen',
    noProps: 'Derzeit keine Regierungsvorlagen verfügbar.',
    propDefault: 'Regierungsvorlage an das Parlament.',
    oppMotions: 'Oppositionsanträge',
    noMotions: 'Derzeit keine Oppositionsanträge verfügbar.',
    author: 'Autor', party: 'Partei',
    motionDefault: 'Parlamentarischer Antrag eines Oppositionsmitglieds.',
    genericContent: 'Inhaltserstellung läuft.',
    monitorDev: 'Entwicklungen und Ergebnisse überwachen',
    committeeDebates: 'Ausschussdebatten',
    committeeDebatesDesc: (n: number): string => `${n} Ausschussberichte für Plenardebatte geplant`,
    govProposals: 'Regierungsvorlagen',
    govProposalsDesc: (n: number): string => `${n} neue Regierungsvorlagen in Prüfung`,
    weekAhead: 'Woche Voraus', committeeReportsTag: 'Ausschussberichte',
    govPropsTag: 'Regierungsvorlagen', oppMotionsTag: 'Oppositionsanträge',
    // Enhanced summary labels
    committeeReport: 'Ausschussbericht',
    on: 'über',
    governmentProposition: 'Regierungsvorlage',
    regarding: 'bezüglich',
    referredTo: 'verwiesen an',
    motionBy: 'Antrag von',
    parliamentaryMotion: 'Parlamentarischer Antrag',
    unknown: 'Unbekannt',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `Die Ausschüsse des schwedischen Reichstags haben ${n} neue Berichte veröffentlicht, die laufende Gesetzgebungsarbeit widerspiegeln.`,
    reportSignificance: 'Dieser Bericht befasst sich mit',
    readFullReport: 'Den vollständigen Bericht lesen',
    propsOverview: (n: number): string => `Die Regierung hat ${n} neue Vorlagen an das Parlament übermittelt.`,
    propSignificance: 'Diese Vorlage betrifft',
    readFullProp: 'Die vollständige Vorlage lesen',
    motionsOverview: (n: number): string => `Oppositionsabgeordnete haben ${n} neue Anträge eingereicht.`,
    motionSignificance: 'Dieser Antrag befasst sich mit',
    readFullMotion: 'Den vollständigen Antrag lesen',
    policyContext: 'Politischer Kontext',
    filedBy: 'Eingereicht von',
    politicalContext: 'Politischer Kontext',
    policyImplications: 'Politische Auswirkungen',
    keyTakeaways: 'Zentrale Erkenntnisse',
    thematicAnalysis: 'Thematische Analyse',
    legislativePipeline: 'Gesetzgebungsverfahren',
    oppositionStrategy: 'Oppositionsstrategie',
    coalitionDynamics: 'Koalitionsdynamik',
    whatThisMeans: 'Was dies bedeutet',
    whyItMatters: 'Warum es wichtig ist',
    committeeBreakdown: (n: number, c: number): string => `Diese Runde von ${n} Ausschussberichten umfasst ${c} verschiedene Ausschüsse.`,
    propsBreakdown: (n: number): string => `Die Regierung hat ${n} neue Vorlagen eingebracht.`,
    motionsBreakdown: (n: number): string => `Oppositionsabgeordnete haben ${n} neue Anträge eingereicht.`
,
    committeeCountContext: (n: number): string => `${n} Berichte dieses Ausschusses signalisieren intensive Gesetzgebungsarbeit.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `Die Parlamentsausschüsse waren in den Bereichen ${committees} und ${extra} weiteren Politikfeldern aktiv.` : `Die Parlamentsausschüsse waren in den Bereichen ${committees} aktiv.`,
    committeeMomentumTakeaway: (n: number): string => `Insgesamt ${n} Berichte zeugen von anhaltendem Gesetzgebungsmomentum.`,
    oppositionStrategyContext: (n: number): string => `Anträge aus ${n} verschiedenen Parteien zeigen die Breite der oppositionellen politischen Kritik.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `Diese ${propCount} Vorlagen betreffen ${domainCount} Politikbereich${domainCount > 1 ? 'e' : ''} und demonstrieren den breiten Gesetzgebungsanspruch der Regierung.`,
    genericOverview: (n: number): string => `In diesem Zeitraum wurden ${n} Dokumente im Parlament behandelt.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} Antrag${n > 1 ? 'e' : ''} eingereicht`,
    otherCommittee: 'Sonstige Ausschüsse',
    otherDocuments: 'Sonstige Dokumente',
    policySignificanceTouches: (domains: string): string => `Betrifft ${domains}.`,
    policySignificanceGeneric: 'Erfordert Ausschussberatung und Kammerdebatte vor einer Entscheidung.',
    processedThisPeriod: 'in dieser Periode behandelt',
    generalMatters: 'Allgemeine Angelegenheiten',
    responsesToProp: 'Antworten auf Regierungsvorlagen',
    independentMotions: 'Sonstige Anträge',
    govEngagement: 'Engagement der Regierungsressorts',
    twitterLabel1: 'Lesezeit',
    twitterLabel2: 'Artikeltyp',
    jobTitle: 'Politischer Geheimdienstanalyst',
    siteDescription: 'Schwedische Parlamentsplattform – politische Aktivität mit systematischer Transparenz verfolgen'
  },
  fr: {
    whyMatters: 'Pourquoi cette semaine est importante',
    whyMattersDefault: 'Cette semaine est marquée par une activité parlementaire significative avec des débats clés, des réunions de commission et des consultations gouvernementales.',
    keyEvents: 'Événements clés cette semaine',
    whatToWatch: 'À suivre',
    latestReports: 'Derniers rapports de commission',
    noReports: 'Aucun rapport de commission disponible pour le moment.',
    committee: 'Commission', document: 'Document',
    reportDefault: 'Rapport de commission sur une affaire parlementaire.',
    govProps: 'Propositions gouvernementales',
    noProps: 'Aucune proposition gouvernementale disponible pour le moment.',
    propDefault: 'Proposition du gouvernement au Parlement.',
    oppMotions: 'Motions d\'opposition',
    noMotions: 'Aucune motion d\'opposition disponible pour le moment.',
    author: 'Auteur', party: 'Parti',
    motionDefault: 'Motion parlementaire d\'un membre de l\'opposition.',
    genericContent: 'Génération de contenu en cours.',
    monitorDev: 'Suivre les développements et les résultats',
    committeeDebates: 'Débats en commission',
    committeeDebatesDesc: (n: number): string => `${n} rapports de commission prévus pour débat en séance`,
    govProposals: 'Propositions gouvernementales',
    govProposalsDesc: (n: number): string => `${n} nouvelles propositions gouvernementales à l'examen`,
    weekAhead: 'Semaine à venir', committeeReportsTag: 'Rapports de commission',
    govPropsTag: 'Propositions gouvernementales', oppMotionsTag: 'Motions d\'opposition',
    // Enhanced summary labels
    committeeReport: 'rapport de commission',
    on: 'sur',
    governmentProposition: 'Proposition gouvernementale',
    regarding: 'concernant',
    referredTo: 'renvoyée à',
    motionBy: 'Motion de',
    parliamentaryMotion: 'Motion parlementaire',
    unknown: 'Inconnu',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `Les commissions du Riksdag suédois ont publié ${n} nouveaux rapports reflétant le travail législatif en cours.`,
    reportSignificance: 'Ce rapport traite de',
    readFullReport: 'Lire le rapport complet',
    propsOverview: (n: number): string => `Le gouvernement a soumis ${n} nouvelles propositions au Parlement.`,
    propSignificance: 'Cette proposition concerne',
    readFullProp: 'Lire la proposition complète',
    motionsOverview: (n: number): string => `Des députés de l'opposition ont déposé ${n} nouvelles motions.`,
    motionSignificance: 'Cette motion traite de',
    readFullMotion: 'Lire la motion complète',
    policyContext: 'Contexte politique',
    filedBy: 'Déposé par',
    politicalContext: 'Contexte politique',
    policyImplications: 'Implications politiques',
    keyTakeaways: 'Points clés',
    thematicAnalysis: 'Analyse thématique',
    legislativePipeline: 'Processus législatif',
    oppositionStrategy: 'Stratégie de l\'opposition',
    coalitionDynamics: 'Dynamique de coalition',
    whatThisMeans: 'Ce que cela signifie',
    whyItMatters: 'Pourquoi c\'est important',
    committeeBreakdown: (n: number, c: number): string => `Ce lot de ${n} rapports de commission couvre ${c} commissions différentes.`,
    propsBreakdown: (n: number): string => `Le gouvernement a soumis ${n} nouvelles propositions.`,
    motionsBreakdown: (n: number): string => `Les députés de l'opposition ont déposé ${n} nouvelles motions.`
,
    committeeCountContext: (n: number): string => `${n} rapports de cette commission témoignent d'un travail législatif intensif.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `Les commissions parlementaires ont été actives dans les domaines ${committees} et ${extra} autres domaines politiques.` : `Les commissions parlementaires ont été actives dans les domaines ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `Un total de ${n} rapports démontre un élan législatif soutenu.`,
    oppositionStrategyContext: (n: number): string => `Des motions de ${n} partis différents révèlent l'étendue de la critique politique de l'opposition.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `Ces ${propCount} propositions touchent à ${domainCount} domaine${domainCount > 1 ? 's' : ''} politique${domainCount > 1 ? 's' : ''}, démontrant l'ambition législative du gouvernement.`,
    genericOverview: (n: number): string => `Durant cette période, ${n} documents ont été traités au parlement.`,
    partyMotionsFiled: (party: string, n: number): string => `${party} : ${n} motion${n > 1 ? 's' : ''} déposée${n > 1 ? 's' : ''}`,
    otherCommittee: 'Autres commissions',
    otherDocuments: 'Autres documents',
    policySignificanceTouches: (domains: string): string => `Touche aux domaines ${domains}.`,
    policySignificanceGeneric: 'Nécessite un examen en commission et un débat en séance avant toute décision.',
    processedThisPeriod: 'traités au cours de cette période',
    generalMatters: 'Questions générales',
    responsesToProp: 'Réponses aux propositions gouvernementales',
    independentMotions: 'Autres motions',
    govEngagement: 'Engagement des ministères',
    twitterLabel1: 'Temps de lecture',
    twitterLabel2: "Type d'article",
    jobTitle: 'Analyste en renseignement politique',
    siteDescription: "Plateforme du Parlement suédois – surveiller l'activité politique avec une transparence systématique"
  },
  es: {
    whyMatters: 'Por qué esta semana es importante',
    whyMattersDefault: 'Esta semana presenta actividad parlamentaria significativa con debates clave, reuniones de comisión y consultas gubernamentales.',
    keyEvents: 'Eventos clave esta semana',
    whatToWatch: 'Qué observar',
    latestReports: 'Últimos informes de comisión',
    noReports: 'No hay informes de comisión disponibles en este momento.',
    committee: 'Comisión', document: 'Documento',
    reportDefault: 'Informe de comisión sobre asunto parlamentario.',
    govProps: 'Proposiciones gubernamentales',
    noProps: 'No hay proposiciones gubernamentales disponibles en este momento.',
    propDefault: 'Propuesta del gobierno al Parlamento.',
    oppMotions: 'Mociones de oposición',
    noMotions: 'No hay mociones de oposición disponibles en este momento.',
    author: 'Autor', party: 'Partido',
    motionDefault: 'Moción parlamentaria de un miembro de la oposición.',
    genericContent: 'Generación de contenido en curso.',
    monitorDev: 'Monitorear desarrollos y resultados',
    committeeDebates: 'Debates en comisión',
    committeeDebatesDesc: (n: number): string => `${n} informes de comisión programados para debate en pleno`,
    govProposals: 'Propuestas gubernamentales',
    govProposalsDesc: (n: number): string => `${n} nuevas proposiciones gubernamentales en revisión`,
    weekAhead: 'Semana próxima', committeeReportsTag: 'Informes de comisión',
    govPropsTag: 'Proposiciones gubernamentales', oppMotionsTag: 'Mociones de oposición',
    // Enhanced summary labels
    committeeReport: 'informe de comisión',
    on: 'sobre',
    governmentProposition: 'Proposición gubernamental',
    regarding: 'referente a',
    referredTo: 'remitida a',
    motionBy: 'Moción de',
    parliamentaryMotion: 'Moción parlamentaria',
    unknown: 'Desconocido',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `Las comisiones del Riksdag sueco han publicado ${n} nuevos informes que reflejan el trabajo legislativo en curso.`,
    reportSignificance: 'Este informe aborda',
    readFullReport: 'Leer el informe completo',
    propsOverview: (n: number): string => `El gobierno ha presentado ${n} nuevas proposiciones al Parlamento.`,
    propSignificance: 'Esta proposición se refiere a',
    readFullProp: 'Leer la proposición completa',
    motionsOverview: (n: number): string => `Diputados de la oposición han presentado ${n} nuevas mociones.`,
    motionSignificance: 'Esta moción aborda',
    readFullMotion: 'Leer la moción completa',
    policyContext: 'Contexto político',
    filedBy: 'Presentada por',
    politicalContext: 'Contexto político',
    policyImplications: 'Implicaciones políticas',
    keyTakeaways: 'Conclusiones clave',
    thematicAnalysis: 'Análisis temático',
    legislativePipeline: 'Proceso legislativo',
    oppositionStrategy: 'Estrategia de la oposición',
    coalitionDynamics: 'Dinámica de coalición',
    whatThisMeans: 'Qué significa esto',
    whyItMatters: 'Por qué es importante',
    committeeBreakdown: (n: number, c: number): string => `Este lote de ${n} informes de comisión abarca ${c} comisiones diferentes.`,
    propsBreakdown: (n: number): string => `El gobierno ha presentado ${n} nuevas proposiciones.`,
    motionsBreakdown: (n: number): string => `Los diputados de la oposición han presentado ${n} nuevas mociones.`
,
    committeeCountContext: (n: number): string => `${n} informes de esta comisión señalan un trabajo legislativo intensivo.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `Las comisiones parlamentarias han estado activas en las áreas de ${committees} y ${extra} dominios políticos más.` : `Las comisiones parlamentarias han estado activas en las áreas de ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `Un total de ${n} informes demuestra un impulso legislativo sostenido.`,
    oppositionStrategyContext: (n: number): string => `Mociones de ${n} partidos diferentes revelan la amplitud de la crítica política de la oposición.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `Estas ${propCount} proposiciones abarcan ${domainCount} dominio${domainCount > 1 ? 's' : ''} político${domainCount > 1 ? 's' : ''}, demostrando la amplia ambición legislativa del gobierno.`,
    genericOverview: (n: number): string => `Durante este período, ${n} documentos fueron procesados en el parlamento.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} moción${n > 1 ? 'es' : ''} presentada${n > 1 ? 's' : ''}`,
    otherCommittee: 'Otras comisiones',
    otherDocuments: 'Otros documentos',
    policySignificanceTouches: (domains: string): string => `Toca los ámbitos de ${domains}.`,
    policySignificanceGeneric: 'Requiere revisión en comisión y debate en cámara antes de tomar una decisión.',
    processedThisPeriod: 'procesados en este período',
    generalMatters: 'Asuntos generales',
    responsesToProp: 'Respuestas a proposiciones del gobierno',
    independentMotions: 'Otras mociones',
    govEngagement: 'Compromiso de los ministerios',
    twitterLabel1: 'Tiempo de lectura',
    twitterLabel2: 'Tipo de artículo',
    jobTitle: 'Analista de inteligencia política',
    siteDescription: 'Plataforma del Parlamento sueco – monitorear la actividad política con transparencia sistemática'
  },
  nl: {
    whyMatters: 'Waarom deze week belangrijk is',
    whyMattersDefault: 'Deze week biedt belangrijke parlementaire activiteit met cruciale debatten, commissievergaderingen en regeringsconsultaties.',
    keyEvents: 'Belangrijke gebeurtenissen deze week',
    whatToWatch: 'Wat te volgen',
    latestReports: 'Nieuwste commissierapporten',
    noReports: 'Geen commissierapporten beschikbaar op dit moment.',
    committee: 'Commissie', document: 'Document',
    reportDefault: 'Commissierapport over parlementaire zaak.',
    govProps: 'Regeringsvoorstellen',
    noProps: 'Geen regeringsvoorstellen beschikbaar op dit moment.',
    propDefault: 'Regeringsvoorstel aan het parlement.',
    oppMotions: 'Oppositiemoties',
    noMotions: 'Geen oppositiemoties beschikbaar op dit moment.',
    author: 'Auteur', party: 'Partij',
    motionDefault: 'Parlementaire motie van een oppositielid.',
    genericContent: 'Inhoud wordt gegenereerd.',
    monitorDev: 'Ontwikkelingen en resultaten volgen',
    committeeDebates: 'Commissiedebatten',
    committeeDebatesDesc: (n: number): string => `${n} commissierapporten gepland voor plenair debat`,
    govProposals: 'Regeringsvoorstellen',
    govProposalsDesc: (n: number): string => `${n} nieuwe regeringsvoorstellen in behandeling`,
    weekAhead: 'Week vooruit', committeeReportsTag: 'Commissierapporten',
    govPropsTag: 'Regeringsvoorstellen', oppMotionsTag: 'Oppositiemoties',
    // Enhanced summary labels
    committeeReport: 'commissierapport',
    on: 'over',
    governmentProposition: 'Regeringsvoorstel',
    regarding: 'betreffende',
    referredTo: 'doorverwezen naar',
    motionBy: 'Motie van',
    parliamentaryMotion: 'Parlementaire motie',
    unknown: 'Onbekend',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `De commissies van de Zweedse Riksdag hebben ${n} nieuwe rapporten gepubliceerd die het lopende wetgevingswerk weerspiegelen.`,
    reportSignificance: 'Dit rapport behandelt',
    readFullReport: 'Lees het volledige rapport',
    propsOverview: (n: number): string => `De regering heeft ${n} nieuwe voorstellen bij het parlement ingediend.`,
    propSignificance: 'Dit voorstel betreft',
    readFullProp: 'Lees het volledige voorstel',
    motionsOverview: (n: number): string => `Oppositieleden hebben ${n} nieuwe moties ingediend.`,
    motionSignificance: 'Deze motie behandelt',
    readFullMotion: 'Lees de volledige motie',
    policyContext: 'Politieke context',
    filedBy: 'Ingediend door',
    politicalContext: 'Politieke context',
    policyImplications: 'Beleidsimplicaties',
    keyTakeaways: 'Belangrijkste bevindingen',
    thematicAnalysis: 'Thematische analyse',
    legislativePipeline: 'Wetgevingsproces',
    oppositionStrategy: 'Oppositiestrategie',
    coalitionDynamics: 'Coalitiedynamiek',
    whatThisMeans: 'Wat dit betekent',
    whyItMatters: 'Waarom het belangrijk is',
    committeeBreakdown: (n: number, c: number): string => `Deze reeks van ${n} commissierapporten bestrijkt ${c} verschillende commissies.`,
    propsBreakdown: (n: number): string => `De regering heeft ${n} nieuwe voorstellen ingediend.`,
    motionsBreakdown: (n: number): string => `Oppositieleden hebben ${n} nieuwe moties ingediend.`
,
    committeeCountContext: (n: number): string => `${n} rapporten van deze commissie signaleren intensief wetgevend werk.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `De parlementaire commissies zijn actief geweest op het gebied van ${committees} en ${extra} verdere beleidsterreinen.` : `De parlementaire commissies zijn actief geweest op het gebied van ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `In totaal ${n} rapporten tonen aanhoudend wetgevend momentum.`,
    oppositionStrategyContext: (n: number): string => `Moties van ${n} verschillende partijen tonen de breedte van de politieke kritiek van de oppositie.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `Deze ${propCount} wetsvoorstellen bestrijken ${domainCount} beleidsterrein${domainCount > 1 ? 'en' : ''}, wat de brede wetgevende ambitie van de regering laat zien.`,
    genericOverview: (n: number): string => `In deze periode zijn ${n} documenten in het parlement behandeld.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} motie${n > 1 ? 's' : ''} ingediend`,
    otherCommittee: 'Overige commissies',
    otherDocuments: 'Overige documenten',
    policySignificanceTouches: (domains: string): string => `Raakt aan ${domains}.`,
    policySignificanceGeneric: 'Vereist commissiebehandeling en plenair debat voor een besluit wordt genomen.',
    processedThisPeriod: 'verwerkt in deze periode',
    generalMatters: 'Algemene zaken',
    responsesToProp: 'Antwoorden op regeringsvoorstellen',
    independentMotions: 'Overige moties',
    govEngagement: 'Betrokkenheid van ministeries',
    twitterLabel1: 'Leestijd',
    twitterLabel2: 'Artikeltype',
    jobTitle: 'Politiek inlichtingenanalist',
    siteDescription: 'Zweeds Parlementsplatform – politieke activiteit volgen met systematische transparantie'
  },
  ar: {
    whyMatters: 'لماذا هذا الأسبوع مهم',
    whyMattersDefault: 'يتميز هذا الأسبوع بنشاط برلماني كبير يشمل مناقشات رئيسية واجتماعات لجان ومشاورات حكومية.',
    keyEvents: 'الأحداث الرئيسية هذا الأسبوع',
    whatToWatch: 'ما يجب متابعته',
    latestReports: 'أحدث تقارير اللجان',
    noReports: 'لا توجد تقارير لجان متاحة حالياً.',
    committee: 'اللجنة', document: 'الوثيقة',
    reportDefault: 'تقرير لجنة عن مسألة برلمانية.',
    govProps: 'مقترحات الحكومة',
    noProps: 'لا توجد مقترحات حكومية متاحة حالياً.',
    propDefault: 'مقترح حكومي للبرلمان.',
    oppMotions: 'اقتراحات المعارضة',
    noMotions: 'لا توجد اقتراحات معارضة متاحة حالياً.',
    author: 'المؤلف', party: 'الحزب',
    motionDefault: 'اقتراح برلماني من عضو في المعارضة.',
    genericContent: 'جارٍ إنشاء المحتوى.',
    monitorDev: 'متابعة التطورات والنتائج',
    committeeDebates: 'مناقشات اللجان',
    committeeDebatesDesc: (n: number): string => `${n} تقارير لجان مجدولة للمناقشة في الجلسة العامة`,
    govProposals: 'مقترحات حكومية',
    govProposalsDesc: (n: number): string => `${n} مقترحات حكومية جديدة قيد المراجعة`,
    weekAhead: 'الأسبوع القادم', committeeReportsTag: 'تقارير اللجان',
    govPropsTag: 'مقترحات الحكومة', oppMotionsTag: 'اقتراحات المعارضة',
    // Enhanced summary labels
    committeeReport: 'تقرير لجنة',
    on: 'بشأن',
    governmentProposition: 'مقترح حكومي',
    regarding: 'فيما يتعلق بـ',
    referredTo: 'محال إلى',
    motionBy: 'اقتراح من',
    parliamentaryMotion: 'اقتراح برلماني',
    unknown: 'غير معروف',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `نشرت لجان البرلمان السويدي ${n} تقارير جديدة تعكس العمل التشريعي الجاري.`,
    reportSignificance: 'يتناول هذا التقرير',
    readFullReport: 'قراءة التقرير الكامل',
    propsOverview: (n: number): string => `قدمت الحكومة ${n} مقترحات جديدة إلى البرلمان.`,
    propSignificance: 'يتعلق هذا المقترح بـ',
    readFullProp: 'قراءة المقترح الكامل',
    motionsOverview: (n: number): string => `قدم أعضاء المعارضة ${n} اقتراحات جديدة.`,
    motionSignificance: 'يتناول هذا الاقتراح',
    readFullMotion: 'قراءة الاقتراح الكامل',
    policyContext: 'السياق السياسي',
    filedBy: 'مقدم من',
    politicalContext: 'السياق السياسي',
    policyImplications: 'الآثار السياسية',
    keyTakeaways: 'النقاط الرئيسية',
    thematicAnalysis: 'التحليل الموضوعي',
    legislativePipeline: 'المسار التشريعي',
    oppositionStrategy: 'استراتيجية المعارضة',
    coalitionDynamics: 'ديناميكيات الائتلاف',
    whatThisMeans: 'ماذا يعني هذا',
    whyItMatters: 'لماذا هذا مهم',
    committeeBreakdown: (n: number, c: number): string => `تغطي هذه الدفعة من ${n} تقارير لجان ${c} لجان مختلفة.`,
    propsBreakdown: (n: number): string => `قدمت الحكومة ${n} مقترحات جديدة.`,
    motionsBreakdown: (n: number): string => `قدم نواب المعارضة ${n} اقتراحات جديدة.`
,
    committeeCountContext: (n: number): string => `${n} تقارير من هذه اللجنة تشير إلى عمل تشريعي مكثف.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `كانت اللجان البرلمانية نشطة في مجالات ${committees} و${extra} مجالات سياسية أخرى.` : `كانت اللجان البرلمانية نشطة في مجالات ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `إجمالي ${n} تقارير يدل على زخم تشريعي مستمر.`,
    oppositionStrategyContext: (n: number): string => `اقتراحات من ${n} أحزاب مختلفة تكشف عن اتساع النقد السياسي للمعارضة.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `تمس هذه المقترحات الـ ${propCount} ${domainCount} مجال${domainCount > 1 ? 'ات' : ''} سياسي${domainCount > 1 ? 'ة' : ''}.`,
    genericOverview: (n: number): string => `خلال هذه الفترة، تمت معالجة ${n} وثائق في البرلمان.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} اقتراح${n > 1 ? 'ات' : ''} مقدمة`,
    otherCommittee: 'لجان أخرى',
    otherDocuments: 'وثائق أخرى',
    policySignificanceTouches: (domains: string): string => `يتعلق بمجالات ${domains}.`,
    policySignificanceGeneric: 'يتطلب مراجعة في اللجنة ونقاش في الجلسة العامة قبل اتخاذ القرار.',
    processedThisPeriod: 'تمت معالجتها في هذه الفترة',
    generalMatters: 'مسائل عامة',
    responsesToProp: 'ردود على مقترحات الحكومة',
    independentMotions: 'اقتراحات أخرى',
    govEngagement: 'مشاركة الوزارات الحكومية',
    twitterLabel1: 'وقت القراءة',
    twitterLabel2: 'نوع المقال',
    jobTitle: 'محلل الاستخبارات السياسية',
    siteDescription: 'منصة البرلمان السويدي – رصد النشاط السياسي بشفافية منهجية'
  },
  he: {
    whyMatters: 'למה השבוע הזה חשוב',
    whyMattersDefault: 'השבוע כולל פעילות פרלמנטרית משמעותית עם דיונים מרכזיים, ישיבות ועדה והתייעצויות ממשלתיות.',
    keyEvents: 'אירועים מרכזיים השבוע',
    whatToWatch: 'מה לעקוב אחריו',
    latestReports: 'דוחות ועדה אחרונים',
    noReports: 'אין דוחות ועדה זמינים כרגע.',
    committee: 'ועדה', document: 'מסמך',
    reportDefault: 'דוח ועדה בנושא פרלמנטרי.',
    govProps: 'הצעות ממשלה',
    noProps: 'אין הצעות ממשלה זמינות כרגע.',
    propDefault: 'הצעת ממשלה לפרלמנט.',
    oppMotions: 'הצעות אופוזיציה',
    noMotions: 'אין הצעות אופוזיציה זמינות כרגע.',
    author: 'מחבר', party: 'מפלגה',
    motionDefault: 'הצעה פרלמנטרית של חבר אופוזיציה.',
    genericContent: 'יצירת תוכן בתהליך.',
    monitorDev: 'לעקוב אחר התפתחויות ותוצאות',
    committeeDebates: 'דיוני ועדות',
    committeeDebatesDesc: (n: number): string => `${n} דוחות ועדה מתוכננים לדיון במליאה`,
    govProposals: 'הצעות ממשלה',
    govProposalsDesc: (n: number): string => `${n} הצעות ממשלה חדשות בבחינה`,
    weekAhead: 'השבוע הקרוב', committeeReportsTag: 'דוחות ועדה',
    govPropsTag: 'הצעות ממשלה', oppMotionsTag: 'הצעות אופוזיציה',
    // Enhanced summary labels
    committeeReport: 'דוח ועדה',
    on: 'על',
    governmentProposition: 'הצעת ממשלה',
    regarding: 'בנוגע ל',
    referredTo: 'הועבר ל',
    motionBy: 'הצעה של',
    parliamentaryMotion: 'הצעה פרלמנטרית',
    unknown: 'לא ידוע',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `ועדות הריקסדאג השוודי פרסמו ${n} דוחות חדשים המשקפים עבודת חקיקה שוטפת.`,
    reportSignificance: 'דוח זה עוסק ב',
    readFullReport: 'קראו את הדוח המלא',
    propsOverview: (n: number): string => `הממשלה הגישה ${n} הצעות חדשות לפרלמנט.`,
    propSignificance: 'הצעה זו נוגעת ל',
    readFullProp: 'קראו את ההצעה המלאה',
    motionsOverview: (n: number): string => `חברי אופוזיציה הגישו ${n} הצעות חדשות.`,
    motionSignificance: 'הצעה זו עוסקת ב',
    readFullMotion: 'קראו את ההצעה המלאה',
    policyContext: 'הקשר מדיני',
    filedBy: 'הוגשה על ידי',
    politicalContext: 'הקשר פוליטי',
    policyImplications: 'השלכות מדיניות',
    keyTakeaways: 'מסקנות מרכזיות',
    thematicAnalysis: 'ניתוח נושאי',
    legislativePipeline: 'תהליך החקיקה',
    oppositionStrategy: 'אסטרטגיית האופוזיציה',
    coalitionDynamics: 'דינמיקת הקואליציה',
    whatThisMeans: 'מה זה אומר',
    whyItMatters: 'למה זה חשוב',
    committeeBreakdown: (n: number, c: number): string => `קבוצה זו של ${n} דוחות ועדה מכסה ${c} ועדות שונות.`,
    propsBreakdown: (n: number): string => `הממשלה הגישה ${n} הצעות חדשות.`,
    motionsBreakdown: (n: number): string => `חברי האופוזיציה הגישו ${n} הצעות חדשות.`
,
    committeeCountContext: (n: number): string => `${n} דוחות מוועדה זו מעידים על עבודת חקיקה אינטנסיבית.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `ועדות הפרלמנט היו פעילות בתחומי ${committees} ו-${extra} תחומי מדיניות נוספים.` : `ועדות הפרלמנט היו פעילות בתחומי ${committees}.`,
    committeeMomentumTakeaway: (n: number): string => `סך של ${n} דוחות מעיד על מומנטום חקיקתי מתמשך.`,
    oppositionStrategyContext: (n: number): string => `הצעות מ-${n} מפלגות שונות חושפות את רוחב הביקורת הפוליטית של האופוזיציה.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `${propCount} הצעות חוק אלה נוגעות ל-${domainCount} תחומ${domainCount > 1 ? 'י' : ''} מדיניות, המדגימות את שאיפת החקיקה הרחבה של הממשלה.`,
    genericOverview: (n: number): string => `במהלך תקופה זו, ${n} מסמכים עברו טיפול בפרלמנט.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n} הצע${n > 1 ? 'ות' : 'ה'} הוגש${n > 1 ? 'ו' : 'ה'}`,
    otherCommittee: 'ועדות אחרות',
    otherDocuments: 'מסמכים אחרים',
    policySignificanceTouches: (domains: string): string => `נוגע בתחומי ${domains}.`,
    policySignificanceGeneric: 'מחייב בחינה בוועדה ודיון במליאה לפני קבלת החלטה.',
    processedThisPeriod: 'עובדו בתקופה זו',
    generalMatters: 'עניינים כלליים',
    responsesToProp: 'תשובות להצעות הממשלה',
    independentMotions: 'הצעות אחרות',
    govEngagement: 'מעורבות משרדי הממשלה',
    twitterLabel1: 'זמן קריאה',
    twitterLabel2: 'סוג כתבה',
    jobTitle: 'אנליסט מודיעין פוליטי',
    siteDescription: 'פלטפורמת הפרלמנט השבדי – מעקב אחר פעילות פוליטית בשקיפות שיטתית'
  },
  ja: {
    whyMatters: 'なぜ今週が重要か',
    whyMattersDefault: '今週は重要な議会活動があり、主要な討論、委員会会議、政府協議が予定されています。',
    keyEvents: '今週の主要イベント',
    whatToWatch: '注目すべきポイント',
    latestReports: '最新の委員会報告',
    noReports: '現在、委員会報告はありません。',
    committee: '委員会', document: '文書',
    reportDefault: '議会事案に関する委員会報告。',
    govProps: '政府提案',
    noProps: '現在、政府提案はありません。',
    propDefault: '政府から議会への提案。',
    oppMotions: '野党動議',
    noMotions: '現在、野党動議はありません。',
    author: '著者', party: '政党',
    motionDefault: '野党議員による議会動議。',
    genericContent: 'コンテンツ生成中。',
    monitorDev: '動向と結果を監視',
    committeeDebates: '委員会討論',
    committeeDebatesDesc: (n: number): string => `${n}件の委員会報告が本会議討論に予定`,
    govProposals: '政府提案',
    govProposalsDesc: (n: number): string => `${n}件の新しい政府提案が審議中`,
    weekAhead: '来週の展望', committeeReportsTag: '委員会報告',
    govPropsTag: '政府提案', oppMotionsTag: '野党動議',
    // Enhanced summary labels
    committeeReport: '委員会報告',
    on: 'について',
    governmentProposition: '政府提案',
    regarding: 'に関する',
    referredTo: 'に付託',
    motionBy: '動議提出者',
    parliamentaryMotion: '議会動議',
    unknown: '不明',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `スウェーデン国会の委員会が${n}件の新しい報告書を発表し、現在進行中の立法作業を反映しています。`,
    reportSignificance: 'この報告書は',
    readFullReport: '報告書全文を読む',
    propsOverview: (n: number): string => `政府は議会に${n}件の新しい提案を提出しました。`,
    propSignificance: 'この提案は',
    readFullProp: '提案全文を読む',
    motionsOverview: (n: number): string => `野党議員が${n}件の新しい動議を提出しました。`,
    motionSignificance: 'この動議は',
    readFullMotion: '動議全文を読む',
    policyContext: '政策的背景',
    filedBy: '提出者',
    politicalContext: '政治的背景',
    policyImplications: '政策への影響',
    keyTakeaways: '主要ポイント',
    thematicAnalysis: 'テーマ別分析',
    legislativePipeline: '立法プロセス',
    oppositionStrategy: '野党の戦略',
    coalitionDynamics: '連立の力学',
    whatThisMeans: 'これが意味すること',
    whyItMatters: 'なぜ重要か',
    committeeBreakdown: (n: number, c: number): string => `この${n}件の委員会報告は${c}の異なる委員会にまたがっています。`,
    propsBreakdown: (n: number): string => `政府は${n}件の新たな法案を提出しました。`,
    motionsBreakdown: (n: number): string => `野党議員が${n}件の新たな動議を提出しました。`
,
    committeeCountContext: (n: number): string => `この委員会からの${n}件の報告書は、集中的な立法作業を示しています。`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `議会の委員会は${committees}および他${extra}の政策分野で活動しています。` : `議会の委員会は${committees}の分野で活動しています。`,
    committeeMomentumTakeaway: (n: number): string => `合計${n}件の報告書は、持続的な立法の勢いを示しています。`,
    oppositionStrategyContext: (n: number): string => `${n}つの異なる政党からの動議は、野党の政治的批判の幅を示しています。`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `これら${propCount}件の法案は${domainCount}つの政策分野に及び、政府の幅広い立法意欲を示しています。`,
    genericOverview: (n: number): string => `この期間中、議会で${n}件の文書が処理されました。`,
    partyMotionsFiled: (party: string, n: number): string => `${party}：${n}件の動議を提出`,
    otherCommittee: 'その他の委員会',
    otherDocuments: 'その他の文書',
    policySignificanceTouches: (domains: string): string => `${domains}に関連します。`,
    policySignificanceGeneric: '決定前に委員会審査と本会議討論が必要です。',
    processedThisPeriod: 'この期間に処理',
    generalMatters: '一般事項',
    responsesToProp: '政府提案への回答',
    independentMotions: 'その他の動議',
    govEngagement: '政府省庁の関与',
    twitterLabel1: '読了時間',
    twitterLabel2: '記事タイプ',
    jobTitle: '政治インテリジェンスアナリスト',
    siteDescription: 'スウェーデン議会プラットフォーム – 体系的な透明性で政治活動を監視'
  },
  ko: {
    whyMatters: '이번 주가 중요한 이유',
    whyMattersDefault: '이번 주에는 주요 토론, 위원회 회의 및 정부 협의를 포함한 중요한 의회 활동이 있습니다.',
    keyEvents: '이번 주 주요 일정',
    whatToWatch: '주목할 사항',
    latestReports: '최신 위원회 보고서',
    noReports: '현재 이용 가능한 위원회 보고서가 없습니다.',
    committee: '위원회', document: '문서',
    reportDefault: '의회 사안에 대한 위원회 보고서.',
    govProps: '정부 법안',
    noProps: '현재 이용 가능한 정부 법안이 없습니다.',
    propDefault: '정부의 의회 법안.',
    oppMotions: '야당 동의',
    noMotions: '현재 이용 가능한 야당 동의가 없습니다.',
    author: '저자', party: '정당',
    motionDefault: '야당 의원의 의회 동의.',
    genericContent: '콘텐츠 생성 중.',
    monitorDev: '동향 및 결과 모니터링',
    committeeDebates: '위원회 토론',
    committeeDebatesDesc: (n: number): string => `${n}개 위원회 보고서가 본회의 토론에 예정`,
    govProposals: '정부 법안',
    govProposalsDesc: (n: number): string => `${n}개 새 정부 법안 검토 중`,
    weekAhead: '다음 주 전망', committeeReportsTag: '위원회 보고서',
    govPropsTag: '정부 법안', oppMotionsTag: '야당 동의',
    // Enhanced summary labels
    committeeReport: '위원회 보고서',
    on: '에 관한',
    governmentProposition: '정부 법안',
    regarding: '에 관하여',
    referredTo: '에 회부',
    motionBy: '동의 제안자',
    parliamentaryMotion: '의회 동의',
    unknown: '알 수 없음',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `스웨덴 의회 위원회가 진행 중인 입법 작업을 반영하는 ${n}개의 새 보고서를 발표했습니다.`,
    reportSignificance: '이 보고서는',
    readFullReport: '전체 보고서 읽기',
    propsOverview: (n: number): string => `정부가 의회에 ${n}개의 새 법안을 제출했습니다.`,
    propSignificance: '이 법안은',
    readFullProp: '전체 법안 읽기',
    motionsOverview: (n: number): string => `야당 의원들이 ${n}개의 새 동의안을 제출했습니다.`,
    motionSignificance: '이 동의안은',
    readFullMotion: '전체 동의안 읽기',
    policyContext: '정책 맥락',
    filedBy: '제출자',
    politicalContext: '정치적 맥락',
    policyImplications: '정책적 시사점',
    keyTakeaways: '핵심 요점',
    thematicAnalysis: '주제별 분석',
    legislativePipeline: '입법 과정',
    oppositionStrategy: '야당 전략',
    coalitionDynamics: '연립 역학',
    whatThisMeans: '이것이 의미하는 바',
    whyItMatters: '왜 중요한가',
    committeeBreakdown: (n: number, c: number): string => `이 ${n}개 위원회 보고서는 ${c}개의 서로 다른 위원회에 걸쳐 있습니다.`,
    propsBreakdown: (n: number): string => `정부가 ${n}개의 새 법안을 제출했습니다.`,
    motionsBreakdown: (n: number): string => `야당 의원들이 ${n}개의 새 동의안을 제출했습니다.`
,
    committeeCountContext: (n: number): string => `이 위원회의 ${n}건의 보고서는 집중적인 입법 작업을 나타냅니다.`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `의회 위원회는 ${committees} 및 ${extra}개의 추가 정책 분야에서 활동했습니다.` : `의회 위원회는 ${committees} 분야에서 활동했습니다.`,
    committeeMomentumTakeaway: (n: number): string => `총 ${n}건의 보고서는 지속적인 입법 추진력을 보여줍니다.`,
    oppositionStrategyContext: (n: number): string => `${n}개 정당의 동의안은 야당의 정치적 비판의 폭을 보여줍니다.`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `이 ${propCount}건의 법안은 ${domainCount}개 정책 영역에 걸쳐 있으며, 정부의 광범위한 입법 야심을 보여줍니다.`,
    genericOverview: (n: number): string => `이 기간 동안 의회에서 ${n}건의 문서가 처리되었습니다.`,
    partyMotionsFiled: (party: string, n: number): string => `${party}: ${n}건의 동의안 제출`,
    otherCommittee: '기타 위원회',
    otherDocuments: '기타 문서',
    policySignificanceTouches: (domains: string): string => `${domains} 분야에 관련됩니다.`,
    policySignificanceGeneric: '결정 전에 위원회 심사와 본회의 토론이 필요합니다.',
    processedThisPeriod: '이 기간에 처리됨',
    generalMatters: '일반 사항',
    responsesToProp: '정부 제안에 대한 응답',
    independentMotions: '기타 동의',
    govEngagement: '정부 부처 참여',
    twitterLabel1: '읽기 시간',
    twitterLabel2: '기사 유형',
    jobTitle: '정치 인텔리전스 분석가',
    siteDescription: '스웨덴 의회 플랫폼 – 체계적인 투명성으로 정치 활동 모니터링'
  },
  zh: {
    whyMatters: '为什么本周很重要',
    whyMattersDefault: '本周有重要的议会活动，包括关键辩论、委员会会议和政府磋商。',
    keyEvents: '本周重要事件',
    whatToWatch: '值得关注的要点',
    latestReports: '最新委员会报告',
    noReports: '目前没有可用的委员会报告。',
    committee: '委员会', document: '文件',
    reportDefault: '关于议会事务的委员会报告。',
    govProps: '政府提案',
    noProps: '目前没有可用的政府提案。',
    propDefault: '政府向议会提交的提案。',
    oppMotions: '反对党动议',
    noMotions: '目前没有可用的反对党动议。',
    author: '作者', party: '政党',
    motionDefault: '反对党议员的议会动议。',
    genericContent: '内容生成中。',
    monitorDev: '监测发展动态和结果',
    committeeDebates: '委员会辩论',
    committeeDebatesDesc: (n: number): string => `${n}份委员会报告安排在全体会议上辩论`,
    govProposals: '政府提案',
    govProposalsDesc: (n: number): string => `${n}项新政府提案正在审查中`,
    weekAhead: '下周展望', committeeReportsTag: '委员会报告',
    govPropsTag: '政府提案', oppMotionsTag: '反对党动议',
    // Enhanced summary labels
    committeeReport: '委员会报告',
    on: '关于',
    governmentProposition: '政府提案',
    regarding: '关于',
    referredTo: '提交至',
    motionBy: '动议提出者',
    parliamentaryMotion: '议会动议',
    unknown: '未知',
    // Analytical narrative labels
    reportsOverview: (n: number): string => `瑞典国会各委员会发布了${n}份新报告，反映了正在进行的立法工作。`,
    reportSignificance: '该报告涉及',
    readFullReport: '阅读完整报告',
    propsOverview: (n: number): string => `政府向议会提交了${n}项新提案。`,
    propSignificance: '该提案涉及',
    readFullProp: '阅读完整提案',
    motionsOverview: (n: number): string => `反对党议员提交了${n}项新动议。`,
    motionSignificance: '该动议涉及',
    readFullMotion: '阅读完整动议',
    policyContext: '政策背景',
    filedBy: '提交者',
    politicalContext: '政治背景',
    policyImplications: '政策影响',
    keyTakeaways: '关键要点',
    thematicAnalysis: '主题分析',
    legislativePipeline: '立法进程',
    oppositionStrategy: '反对党策略',
    coalitionDynamics: '联盟动态',
    whatThisMeans: '这意味着什么',
    whyItMatters: '为什么重要',
    committeeBreakdown: (n: number, c: number): string => `这批${n}份委员会报告涵盖${c}个不同委员会。`,
    propsBreakdown: (n: number): string => `政府提交了${n}项新提案。`,
    motionsBreakdown: (n: number): string => `反对党议员提交了${n}项新动议。`
,
    committeeCountContext: (n: number): string => `该委员会的${n}份报告表明密集的立法工作。`,
    committeeActivityTakeaway: (committees: string, extra: number): string => extra > 0 ? `议会委员会在${committees}以及其他${extra}个政策领域积极开展工作。` : `议会委员会在${committees}领域积极开展工作。`,
    committeeMomentumTakeaway: (n: number): string => `共${n}份报告展示了持续的立法势头。`,
    oppositionStrategyContext: (n: number): string => `来自${n}个不同政党的动议显示了反对派政治批评的广度。`,
    policyImplicationsContext: (propCount: number, domainCount: number): string => `这${propCount}项提案涉及${domainCount}个政策领域，展示了政府广泛的立法雄心。`,
    genericOverview: (n: number): string => `在此期间，议会处理了${n}份文件。`,
    partyMotionsFiled: (party: string, n: number): string => `${party}：提交了${n}项动议`,
    otherCommittee: '其他委员会',
    otherDocuments: '其他文件',
    policySignificanceTouches: (domains: string): string => `涉及${domains}领域。`,
    policySignificanceGeneric: '在作出决定之前需要委员会审查和全体辩论。',
    processedThisPeriod: '本期处理',
    generalMatters: '一般事项',
    responsesToProp: '对政府提案的回应',
    independentMotions: '其他动议',
    govEngagement: '政府部门参与',
    twitterLabel1: '阅读时间',
    twitterLabel2: '文章类型',
    jobTitle: '政治情报分析师',
    siteDescription: '瑞典议会平台 – 以系统透明度监测政治活动'
  }
};
